project_id = "yeuwpuzbccqnqdlnjhfm"

[functions.resend-invite]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.send-request-confirmation]
verify_jwt = false

[functions.send-engagement-emails]
verify_jwt = false

[functions.send-referral-email]
verify_jwt = false

[functions.send-reengagement-email]
verify_jwt = false

[functions.send-beta-feedback-email]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.push-to-sfmc]
verify_jwt = false

[functions.extract-semantics]
verify_jwt = true

[functions.track-email-click]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.send-demo-request]
verify_jwt = false

[functions.parse-web-sections]
verify_jwt = false

[functions.analyze-web-content]
verify_jwt = false

[functions.parse-story]
verify_jwt = true

[functions.parse-fact-book]
verify_jwt = true

[functions.firecrawl-search]
verify_jwt = false

[functions.extract-article-contacts]
verify_jwt = false

[functions.find-linkedin-profile]
verify_jwt = false

[functions.generate-outreach-message]
verify_jwt = false

[functions.send-prospect-email]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.organize-scratchpad]
verify_jwt = false
