project_id = "yeuwpuzbccqnqdlnjhfm"

[functions.resend-invite]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = false

[functions.send-request-confirmation]
verify_jwt = false

[functions.send-engagement-emails]
verify_jwt = false

[functions.send-referral-email]
verify_jwt = false

[functions.send-reengagement-email]
verify_jwt = false