project_id = "souggluacorfgswhphsr"

[functions.evaluate-message]
verify_jwt = false

[functions.generate-message]
verify_jwt = false

[functions.playground-chat]
verify_jwt = false

[functions.analyze-voice]
verify_jwt = false
