import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { corsHeaders } from "../_shared/resilience.ts";

// Map CampusVoice channels to Slate Deliver communication types
const SLATE_COMM_TYPES: Record<string, { type: string; label: string }> = {
  email: { type: "email", label: "Email" },
  sms: { type: "sms", label: "SMS/Text" },
  "direct-mail": { type: "letter", label: "Letter" },
  "phone-call": { type: "call", label: "Phone Call" },
  "landing-page": { type: "page", label: "Page" },
  portal: { type: "email", label: "Portal Notification" },
  "social-media": { type: "email", label: "Social Media Draft" },
  "digital-ad-search": { type: "email", label: "Search Ad Draft" },
  "digital-ad-social": { type: "email", label: "Social Ad Draft" },
  "news-article": { type: "email", label: "News Article Draft" },
  "talking-points": { type: "email", label: "Talking Points Draft" },
  "case-for-care": { type: "email", label: "Case for Support Draft" },
};

interface PushToSlateRequest {
  slateSubdomain: string;
  slateApiKey: string;
  content: string;
  name: string;
  channel: string;
  folderId?: string;
  audience?: string;
  subject?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const {
      slateSubdomain,
      slateApiKey,
      content,
      name,
      channel,
      folderId,
      audience,
      subject,
    }: PushToSlateRequest = await req.json();

    // Validate required fields
    if (!slateSubdomain || !slateApiKey || !content || !name) {
      return new Response(
        JSON.stringify({
          error: "Missing required fields: slateSubdomain, slateApiKey, content, name",
          code: "VALIDATION_ERROR",
          retryable: false,
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Pushing content to Slate subdomain: ${slateSubdomain}`);
    console.log(`Content name: ${name}, Channel: ${channel}`);

    const commType = SLATE_COMM_TYPES[channel] || SLATE_COMM_TYPES["email"];

    // Build the Slate Deliver API payload
    // Slate uses a REST API at https://{subdomain}.technolutions.net/api/v1/
    const slateBaseUrl = `https://${slateSubdomain}.technolutions.net`;

    // Step 1: Authenticate — Slate uses API key auth via header
    // Test the connection by hitting the query endpoint
    const testUrl = `${slateBaseUrl}/api/v1/query?cmd=ping`;
    console.log(`Testing Slate connection at: ${testUrl}`);

    const testResponse = await fetch(testUrl, {
      method: "GET",
      headers: {
        Authorization: `Bearer ${slateApiKey}`,
        "Content-Type": "application/json",
      },
      signal: AbortSignal.timeout(15000),
    });

    if (!testResponse.ok) {
      const errText = await testResponse.text();
      console.error("Slate auth test failed:", testResponse.status, errText);
      return new Response(
        JSON.stringify({
          error: "Slate authentication failed. Please check your subdomain and API key.",
          code: "AUTH_FAILED",
          retryable: false,
        }),
        { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Step 2: Create a Deliver mailing/communication via the Slate API
    // Using the Slate Deliver API to create a new mailing
    const deliverPayload: Record<string, unknown> = {
      name: name,
      type: commType.type,
      status: "draft",
      body: content,
      folder: folderId || null,
    };

    // Add subject for email-type communications
    if (subject && (commType.type === "email" || channel === "email")) {
      deliverPayload.subject = subject;
    }

    // Add audience tag if provided
    if (audience) {
      deliverPayload.description = `Generated by CampusVoice for audience: ${audience}`;
    } else {
      deliverPayload.description = "Generated by CampusVoice";
    }

    const deliverUrl = `${slateBaseUrl}/api/v1/deliver/mailing`;
    console.log(`Creating Slate Deliver mailing at: ${deliverUrl}`);

    const deliverResponse = await fetch(deliverUrl, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${slateApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(deliverPayload),
      signal: AbortSignal.timeout(15000),
    });

    if (!deliverResponse.ok) {
      const deliverError = await deliverResponse.text();
      console.error("Slate Deliver creation failed:", deliverResponse.status, deliverError);

      // Provide helpful error messages
      if (deliverResponse.status === 403) {
        return new Response(
          JSON.stringify({
            error: "Insufficient permissions. Your Slate API key needs Deliver write access.",
            code: "PERMISSION_DENIED",
            retryable: false,
          }),
          { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({
          error: "Failed to create mailing in Slate Deliver.",
          code: "SLATE_ERROR",
          retryable: true,
          details: deliverError,
        }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const deliverData = await deliverResponse.json();
    console.log("Successfully created Slate Deliver mailing:", deliverData.id || deliverData);

    return new Response(
      JSON.stringify({
        success: true,
        mailingId: deliverData.id,
        mailingName: name,
        communicationType: commType.label,
        message: `Content successfully pushed to Slate Deliver as "${name}"`,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error in push-to-slate function:", error);

    if (error instanceof DOMException && error.name === "AbortError") {
      return new Response(
        JSON.stringify({
          error: "Connection to Slate timed out. Please check your subdomain.",
          code: "TIMEOUT",
          retryable: true,
        }),
        { status: 504, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const errorMessage = error instanceof Error ? error.message : "Internal server error";
    return new Response(
      JSON.stringify({ error: errorMessage, code: "INTERNAL_ERROR", retryable: false }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
