import type { IndustryVocabulary } from '@/types/industry';

export const enterpriseVocabulary: IndustryVocabulary = {
  tenantType: 'enterprise',
  labels: {
    organization: 'Company',
    organizationShort: 'Co.',
    organizationPlural: 'Companies',
    organizationSettings: 'Organization Settings',
    organizationAdmin: 'Organization Admin',
    organizationUser: 'Team Member',
    primaryAudience: 'Customers',
    primaryAudienceSingular: 'Customer',
    supporter: 'Investor',
    alumnus: 'Former Customer',
    alumniPlural: 'Former Customers',
    staff: 'Employees',
    leader: 'CEO',
    leaderTitle: 'Chief Executive Officer',
    subUnit: 'Division',
    subUnitPlural: 'Divisions',
    location: 'Office',
    locationPlural: 'Offices',
    enrollment: 'Onboarding',
    graduation: 'Completion',
    term: 'Quarter',
    photography: 'Brand Photography',
    storyBank: 'Success Stories',
    factBook: 'Key Metrics',
    industryContext: 'enterprise brand management',
    contentStyle: 'corporate brand communications',
  },
  audiences: [
    { id: 'prospect', label: 'Sales Lead', description: 'Prospective customer or client' },
    { id: 'new-customer', label: 'New Customer', description: 'Recently acquired customer' },
    { id: 'active-customer', label: 'Active Customer', description: 'Existing, engaged customer' },
    { id: 'at-risk-churn', label: 'At-Risk Customer', description: 'Customer showing churn signals' },
    { id: 'partner', label: 'Channel Partner', description: 'Distribution or reseller partner' },
    { id: 'employee', label: 'Employee', description: 'Internal team member' },
    { id: 'executive', label: 'Executive Stakeholder', description: 'C-suite or senior leadership' },
    { id: 'investor', label: 'Investor', description: 'Shareholders and investors' },
    { id: 'media', label: 'Media & Press', description: 'Journalists and media contacts' },
    { id: 'general', label: 'General', description: 'Broad market audience' },
  ],
  cohorts: [
    { id: 'enterprise-tier', label: 'Enterprise Tier', audienceIds: ['active-customer', 'prospect'] },
    { id: 'smb-tier', label: 'SMB Tier', audienceIds: ['active-customer', 'prospect'] },
    { id: 'strategic-account', label: 'Strategic Account', audienceIds: ['active-customer'] },
    { id: 'renewal-due', label: 'Renewal Due', audienceIds: ['active-customer', 'at-risk-churn'] },
    { id: 'new-hire', label: 'New Hire', audienceIds: ['employee'] },
    { id: 'remote-team', label: 'Remote Team', audienceIds: ['employee'] },
    { id: 'regional-manager', label: 'Regional Manager', audienceIds: ['employee', 'partner'] },
    { id: 'certified-partner', label: 'Certified Partner', audienceIds: ['partner'] },
    { id: 'none', label: 'No specific segment', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Brand Awareness', description: 'General brand awareness campaign', category: 'Marketing' },
    { id: 'product-launch', label: 'Product Launch', description: 'New product or feature announcement', category: 'Marketing' },
    { id: 'seasonal-promo', label: 'Seasonal Promotion', description: 'Seasonal or holiday campaign', category: 'Marketing' },
    { id: 'lead-nurture', label: 'Lead Nurture', description: 'Nurturing prospects through the funnel', category: 'Sales' },
    { id: 'onboarding', label: 'Customer Onboarding', description: 'New customer welcome and setup', category: 'Success' },
    { id: 'qbr', label: 'Quarterly Business Review', description: 'Quarterly review and check-in', category: 'Success' },
    { id: 'contract-renewal', label: 'Contract Renewal', description: 'Upcoming renewal outreach', category: 'Sales' },
    { id: 'upsell-cross-sell', label: 'Upsell / Cross-Sell', description: 'Expansion opportunity', category: 'Sales' },
    { id: 'win-back', label: 'Win-Back', description: 'Re-engaging churned or lapsed customers', category: 'Marketing' },
    { id: 'event-promotion', label: 'Event Promotion', description: 'Conference, webinar, or event', category: 'Marketing' },
    { id: 'compliance-update', label: 'Compliance Update', description: 'Regulatory or policy update', category: 'Operations' },
    { id: 'internal-comms', label: 'Internal Communications', description: 'Company-wide announcement', category: 'Internal' },
    { id: 'partner-enablement', label: 'Partner Enablement', description: 'Partner training or resource distribution', category: 'Channel' },
    { id: 'crisis-comms', label: 'Crisis Communications', description: 'Urgent or sensitive communications', category: 'Operations' },
  ],
  domains: [
    { id: 'product', label: 'Product / Service', description: 'Product features, updates, education' },
    { id: 'sales', label: 'Sales', description: 'Pipeline, proposals, deal communications' },
    { id: 'customer-success', label: 'Customer Success', description: 'Retention, satisfaction, growth' },
    { id: 'marketing', label: 'Marketing', description: 'Brand, demand gen, content' },
    { id: 'pricing-billing', label: 'Pricing & Billing', description: 'Pricing changes, invoicing, payments' },
    { id: 'hr-culture', label: 'HR & Culture', description: 'Employee experience and culture' },
    { id: 'operations', label: 'Operations', description: 'Logistics, facilities, processes' },
    { id: 'compliance', label: 'Compliance & Legal', description: 'Regulatory, legal, policy' },
    { id: 'partnerships', label: 'Partnerships', description: 'Channel and strategic partnerships' },
  ],
  goals: [
    { id: 'purchase', label: 'Purchase', description: 'Drive a buying decision' },
    { id: 'renew', label: 'Renew', description: 'Renew subscription or contract' },
    { id: 'upgrade', label: 'Upgrade', description: 'Move to a higher tier' },
    { id: 'activate', label: 'Activate', description: 'Get started with product/service' },
    { id: 'register', label: 'Register', description: 'Sign up for an event or program' },
    { id: 'refer', label: 'Refer', description: 'Refer new customers or partners' },
    { id: 'respond', label: 'Respond', description: 'Reply or provide feedback' },
    { id: 'attend', label: 'Attend', description: 'Attend event or meeting' },
    { id: 'acknowledge', label: 'Acknowledge', description: 'Read and confirm' },
    { id: 'engage', label: 'Engage', description: 'Interact with content or community' },
  ],
  departments: [
    { id: 'marketing', label: 'Marketing', description: 'Brand and demand generation', icon: 'megaphone' },
    { id: 'sales', label: 'Sales', description: 'Revenue and pipeline', icon: 'target' },
    { id: 'customer-success', label: 'Customer Success', description: 'Retention and growth', icon: 'heart' },
    { id: 'product', label: 'Product', description: 'Product management and development', icon: 'briefcase' },
    { id: 'operations', label: 'Operations', description: 'Business operations', icon: 'building' },
    { id: 'hr', label: 'Human Resources', description: 'People and culture', icon: 'users' },
    { id: 'executive', label: 'Executive Office', description: 'C-suite communications', icon: 'building-2' },
    { id: 'partnerships', label: 'Partnerships', description: 'Channel and alliances', icon: 'handshake' },
  ],
  storyTypes: [
    { id: 'customer', label: 'Customer', icon: 'User' },
    { id: 'partner', label: 'Partner', icon: 'Handshake' },
    { id: 'employee', label: 'Employee', icon: 'Users' },
    { id: 'executive', label: 'Executive', icon: 'Crown' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'innovation', label: 'Innovation', icon: 'Lightbulb' },
  ],
  relevantConfigFields: [
    'institutionName', 'slogans', 'emailDomain',
    'primaryCTAs', 'secondaryCTAs', 'urgentCTAs',
    'primaryContactEmail', 'primaryContactPhone',
    'websiteLinks', 'socialMediaHandles',
    'toneRules', 'wordsToAvoid', 'preferredPhrases',
  ],
  classificationOptions: [
    { value: 'global-enterprise', label: 'Global Enterprise', description: 'Multi-national corporation with regional operations' },
    { value: 'mid-market', label: 'Mid-Market', description: 'Medium-sized company with growth ambitions' },
    { value: 'startup-scaleup', label: 'Startup / Scale-Up', description: 'Fast-growing company building brand presence' },
    { value: 'public-company', label: 'Public Company', description: 'Publicly traded corporation' },
    { value: 'private-company', label: 'Private Company', description: 'Privately held enterprise' },
  ],
};
