import type { IndustryVocabulary } from '@/types/industry';

export const financialVocabulary: IndustryVocabulary = {
  tenantType: 'financial',
  labels: {
    organization: 'Institution',
    organizationShort: 'Inst.',
    organizationPlural: 'Institutions',
    organizationSettings: 'Institution Settings',
    organizationAdmin: 'Institution Admin',
    organizationUser: 'Team Member',
    primaryAudience: 'Clients',
    primaryAudienceSingular: 'Client',
    supporter: 'Investor',
    alumnus: 'Former Client',
    alumniPlural: 'Former Clients',
    staff: 'Advisors & Staff',
    leader: 'President',
    leaderTitle: 'President',
    subUnit: 'Branch',
    subUnitPlural: 'Branches',
    location: 'Branch',
    locationPlural: 'Branches',
    enrollment: 'Account Opening',
    graduation: 'Maturity',
    term: 'Quarter',
    photography: 'Brand Photography',
    storyBank: 'Client Stories',
    factBook: 'Performance Metrics',
    organizationProfile: 'Institution Profile',
    industryContext: 'financial services communications',
    contentStyle: 'professional financial services brand communications',
  },
  audiences: [
    { id: 'prospect', label: 'Prospect', description: 'Prospective client or account holder' },
    { id: 'retail-client', label: 'Retail Client', description: 'Individual account holder' },
    { id: 'wealth-client', label: 'Wealth Client', description: 'High-net-worth individual' },
    { id: 'business-client', label: 'Business Client', description: 'Commercial or business account' },
    { id: 'advisor', label: 'Financial Advisor', description: 'Field advisors and agents' },
    { id: 'employee', label: 'Employee', description: 'Internal staff' },
    { id: 'branch-manager', label: 'Branch Manager', description: 'Branch leadership' },
    { id: 'community', label: 'Community', description: 'Community and CRA audience' },
    { id: 'general', label: 'General', description: 'Broad market audience' },
  ],
  cohorts: [
    { id: 'new-account', label: 'New Account', audienceIds: ['retail-client', 'business-client'] },
    { id: 'at-risk', label: 'At-Risk Client', audienceIds: ['retail-client', 'wealth-client'] },
    { id: 'high-value', label: 'High-Value Client', audienceIds: ['retail-client', 'wealth-client'] },
    { id: 'digital-first', label: 'Digital-First', audienceIds: ['retail-client', 'prospect'] },
    { id: 'pre-retiree', label: 'Pre-Retiree', audienceIds: ['retail-client', 'wealth-client'] },
    { id: 'small-business', label: 'Small Business', audienceIds: ['business-client'] },
    { id: 'none', label: 'No specific segment', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Brand Awareness', description: 'Brand positioning campaign', category: 'Marketing' },
    { id: 'account-opening', label: 'Account Opening', description: 'New account welcome', category: 'Onboarding' },
    { id: 'product-launch', label: 'Product Launch', description: 'New product or service', category: 'Marketing' },
    { id: 'rate-change', label: 'Rate Change', description: 'Interest rate or fee update', category: 'Operations' },
    { id: 'annual-review', label: 'Annual Review', description: 'Client annual review meeting', category: 'Advisory' },
    { id: 'compliance-notice', label: 'Compliance Notice', description: 'Regulatory disclosure', category: 'Compliance' },
    { id: 'community-reinvestment', label: 'Community Reinvestment', description: 'CRA and community programs', category: 'Community' },
    { id: 'digital-adoption', label: 'Digital Adoption', description: 'Digital banking promotion', category: 'Marketing' },
    { id: 'branch-event', label: 'Branch Event', description: 'Local branch event or seminar', category: 'Events' },
    { id: 'internal-comms', label: 'Internal Communications', description: 'Staff and advisor updates', category: 'Internal' },
    { id: 'crisis-comms', label: 'Crisis Communications', description: 'Fraud alerts, security', category: 'Operations' },
  ],
  domains: [
    { id: 'marketing', label: 'Marketing', description: 'Brand and acquisition' },
    { id: 'advisory', label: 'Advisory', description: 'Client advisory and planning' },
    { id: 'product', label: 'Products & Services', description: 'Banking and investment products' },
    { id: 'operations', label: 'Operations', description: 'Account services and support' },
    { id: 'compliance', label: 'Compliance & Legal', description: 'Regulatory and legal communications' },
    { id: 'community', label: 'Community', description: 'CRA and community engagement' },
    { id: 'hr-culture', label: 'HR & Culture', description: 'Employee experience' },
    { id: 'digital', label: 'Digital Banking', description: 'Digital channel adoption' },
  ],
  goals: [
    { id: 'open-account', label: 'Open Account', description: 'Start a new account' },
    { id: 'schedule-review', label: 'Schedule Review', description: 'Book advisory meeting' },
    { id: 'activate', label: 'Activate', description: 'Set up digital banking' },
    { id: 'apply', label: 'Apply', description: 'Apply for loan or credit' },
    { id: 'register', label: 'Register', description: 'Sign up for event or service' },
    { id: 'respond', label: 'Respond', description: 'Reply or confirm' },
    { id: 'refer', label: 'Refer', description: 'Refer a friend or business' },
    { id: 'attend', label: 'Attend', description: 'Attend seminar or event' },
    { id: 'engage', label: 'Engage', description: 'Interact with content' },
  ],
  departments: [
    { id: 'marketing', label: 'Marketing', description: 'Brand and demand generation', icon: 'megaphone' },
    { id: 'retail-banking', label: 'Retail Banking', description: 'Consumer banking', icon: 'landmark' },
    { id: 'wealth-management', label: 'Wealth Management', description: 'Advisory and planning', icon: 'piggy-bank' },
    { id: 'commercial', label: 'Commercial Banking', description: 'Business banking', icon: 'building' },
    { id: 'compliance', label: 'Compliance', description: 'Regulatory affairs', icon: 'shield' },
    { id: 'operations', label: 'Operations', description: 'Branch and back office', icon: 'briefcase' },
    { id: 'digital', label: 'Digital', description: 'Digital banking and innovation', icon: 'globe' },
    { id: 'executive', label: 'Executive Office', description: 'Leadership communications', icon: 'building-2' },
  ],
  storyTypes: [
    { id: 'client', label: 'Client', icon: 'User' },
    { id: 'advisor', label: 'Advisor', icon: 'Briefcase' },
    { id: 'employee', label: 'Employee', icon: 'Users' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'innovation', label: 'Innovation', icon: 'Lightbulb' },
  ],
  relevantConfigFields: [
    'institutionName', 'slogans', 'emailDomain',
    'primaryCTAs', 'primaryContactEmail', 'primaryContactPhone',
    'websiteLinks', 'socialMediaHandles',
    'toneRules', 'wordsToAvoid', 'preferredPhrases',
  ],
  classificationOptions: [
    { value: 'commercial-bank', label: 'Commercial Bank', description: 'Full-service commercial bank' },
    { value: 'credit-union', label: 'Credit Union', description: 'Member-owned cooperative' },
    { value: 'wealth-management', label: 'Wealth Management', description: 'Investment and advisory firm' },
    { value: 'insurance-company', label: 'Insurance Company', description: 'Insurance provider' },
    { value: 'fintech', label: 'FinTech', description: 'Financial technology company' },
    { value: 'community-bank', label: 'Community Bank', description: 'Community-focused local bank' },
  ],
};
