import type { IndustryVocabulary } from '@/types/industry';

export const franchiseVocabulary: IndustryVocabulary = {
  tenantType: 'franchise',
  labels: {
    organization: 'Brand',
    organizationShort: 'Brand',
    organizationPlural: 'Brands',
    organizationSettings: 'Brand Settings',
    organizationAdmin: 'Brand Admin',
    organizationUser: 'Team Member',
    primaryAudience: 'Customers',
    primaryAudienceSingular: 'Customer',
    supporter: 'Partner',
    alumnus: 'Former Franchisee',
    alumniPlural: 'Former Franchisees',
    staff: 'Team Members',
    leader: 'Brand Director',
    leaderTitle: 'VP of Brand',
    subUnit: 'Region',
    subUnitPlural: 'Regions',
    location: 'Location',
    locationPlural: 'Locations',
    enrollment: 'Onboarding',
    graduation: 'Certification',
    term: 'Quarter',
    photography: 'Brand Photography',
    storyBank: 'Success Stories',
    factBook: 'Performance Metrics',
    industryContext: 'franchise brand management',
    contentStyle: 'franchise marketing and local dealer communications',
  },
  audiences: [
    { id: 'consumer', label: 'Consumer', description: 'End consumer or retail customer' },
    { id: 'prospect-customer', label: 'Prospective Customer', description: 'Potential customer in the market' },
    { id: 'loyal-customer', label: 'Loyal Customer', description: 'Repeat, high-value customer' },
    { id: 'franchisee', label: 'Franchisee / Dealer', description: 'Franchise owner or authorized dealer' },
    { id: 'prospect-franchisee', label: 'Prospective Franchisee', description: 'Interested franchise candidate' },
    { id: 'regional-manager', label: 'Regional Manager', description: 'Regional or district manager' },
    { id: 'employee', label: 'Location Staff', description: 'Frontline or location-level employee' },
    { id: 'vendor', label: 'Vendor / Supplier', description: 'Supply chain partners' },
    { id: 'general', label: 'General Market', description: 'Broad market audience' },
  ],
  cohorts: [
    { id: 'new-location', label: 'New Location', audienceIds: ['franchisee'] },
    { id: 'underperforming', label: 'Underperforming Location', audienceIds: ['franchisee'] },
    { id: 'top-performer', label: 'Top Performer', audienceIds: ['franchisee'] },
    { id: 'multi-unit', label: 'Multi-Unit Owner', audienceIds: ['franchisee'] },
    { id: 'urban-market', label: 'Urban Market', audienceIds: ['consumer', 'prospect-customer'] },
    { id: 'suburban-market', label: 'Suburban Market', audienceIds: ['consumer', 'prospect-customer'] },
    { id: 'seasonal-worker', label: 'Seasonal Worker', audienceIds: ['employee'] },
    { id: 'none', label: 'No specific segment', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Brand Awareness', description: 'National brand campaign', category: 'Brand' },
    { id: 'grand-opening', label: 'Grand Opening', description: 'New location launch', category: 'Local' },
    { id: 'seasonal-promo', label: 'Seasonal Promotion', description: 'Seasonal or holiday offer', category: 'Marketing' },
    { id: 'local-campaign', label: 'Local Campaign', description: 'Geo-targeted local marketing', category: 'Local' },
    { id: 'product-launch', label: 'Product / Menu Launch', description: 'New product or service rollout', category: 'Marketing' },
    { id: 'franchisee-onboarding', label: 'Franchisee Onboarding', description: 'New franchisee welcome and training', category: 'Operations' },
    { id: 'compliance-update', label: 'Brand Compliance Update', description: 'Standards and guidelines update', category: 'Operations' },
    { id: 'annual-convention', label: 'Annual Convention', description: 'Annual franchise meeting', category: 'Events' },
    { id: 'performance-review', label: 'Performance Review', description: 'Quarterly location reviews', category: 'Operations' },
    { id: 'customer-loyalty', label: 'Loyalty Program', description: 'Rewards and loyalty campaigns', category: 'Marketing' },
    { id: 'crisis-comms', label: 'Crisis Communications', description: 'Urgent brand-wide messaging', category: 'Operations' },
    { id: 'remodel-refresh', label: 'Remodel / Refresh', description: 'Location renovation communications', category: 'Local' },
  ],
  domains: [
    { id: 'brand-marketing', label: 'Brand Marketing', description: 'National brand campaigns and positioning' },
    { id: 'local-marketing', label: 'Local Marketing', description: 'Location-level promotions and outreach' },
    { id: 'operations', label: 'Operations', description: 'Standards, compliance, and procedures' },
    { id: 'training', label: 'Training & Enablement', description: 'Staff and franchisee training' },
    { id: 'product', label: 'Product / Service', description: 'Product info, launches, updates' },
    { id: 'customer-experience', label: 'Customer Experience', description: 'Service quality and satisfaction' },
    { id: 'supply-chain', label: 'Supply Chain', description: 'Vendor and logistics communications' },
    { id: 'hr-culture', label: 'HR & Culture', description: 'Employment and team culture' },
  ],
  goals: [
    { id: 'drive-traffic', label: 'Drive Traffic', description: 'Bring customers to location' },
    { id: 'purchase', label: 'Purchase', description: 'Drive a sale or transaction' },
    { id: 'redeem-offer', label: 'Redeem Offer', description: 'Use a coupon or promotion' },
    { id: 'register', label: 'Register', description: 'Sign up for loyalty or event' },
    { id: 'comply', label: 'Comply', description: 'Follow brand standards' },
    { id: 'attend', label: 'Attend', description: 'Attend training or event' },
    { id: 'activate', label: 'Activate', description: 'Launch a new initiative' },
    { id: 'refer', label: 'Refer', description: 'Refer new customers or franchisees' },
    { id: 'engage', label: 'Engage', description: 'Interact with brand content' },
  ],
  departments: [
    { id: 'brand-marketing', label: 'Brand Marketing', description: 'National marketing team' },
    { id: 'field-marketing', label: 'Field Marketing', description: 'Regional and local marketing' },
    { id: 'franchise-development', label: 'Franchise Development', description: 'New franchisee recruitment' },
    { id: 'operations', label: 'Operations', description: 'Standards and compliance' },
    { id: 'training', label: 'Training', description: 'Learning and development' },
    { id: 'executive', label: 'Executive Office', description: 'C-suite and leadership' },
    { id: 'supply-chain', label: 'Supply Chain', description: 'Procurement and logistics' },
  ],
  storyTypes: [
    { id: 'customer', label: 'Customer', icon: 'User' },
    { id: 'franchisee', label: 'Franchisee', icon: 'Store' },
    { id: 'employee', label: 'Team Member', icon: 'Users' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'brand', label: 'Brand Heritage', icon: 'Award' },
    { id: 'innovation', label: 'Innovation', icon: 'Lightbulb' },
  ],
  relevantConfigFields: [
    'institutionName', 'slogans', 'emailDomain',
    'primaryCTAs', 'secondaryCTAs', 'urgentCTAs',
    'primaryContactEmail', 'primaryContactPhone',
    'websiteLinks', 'socialMediaHandles',
    'toneRules', 'wordsToAvoid', 'preferredPhrases',
  ],
  classificationOptions: [
    { value: 'national-franchise', label: 'National Franchise', description: 'Franchise network operating across the country' },
    { value: 'global-franchise', label: 'Global Franchise', description: 'International franchise with multi-country operations' },
    { value: 'regional-chain', label: 'Regional Chain', description: 'Regional brand with multiple locations' },
    { value: 'dealer-network', label: 'Dealer Network', description: 'Manufacturer with authorized dealer/reseller network' },
    { value: 'licensing-model', label: 'Licensing Model', description: 'Brand licensing with independent operators' },
  ],
};
