import type { IndustryVocabulary } from '@/types/industry';

export const healthcareVocabulary: IndustryVocabulary = {
  tenantType: 'healthcare',
  labels: {
    organization: 'Health System',
    organizationShort: 'System',
    organizationPlural: 'Health Systems',
    organizationSettings: 'System Settings',
    organizationAdmin: 'System Admin',
    organizationUser: 'Team Member',
    primaryAudience: 'Patients',
    primaryAudienceSingular: 'Patient',
    supporter: 'Benefactor',
    alumnus: 'Former Patient',
    alumniPlural: 'Former Patients',
    staff: 'Clinical & Admin Staff',
    leader: 'Chief Medical Officer',
    leaderTitle: 'CMO',
    subUnit: 'Facility',
    subUnitPlural: 'Facilities',
    location: 'Facility',
    locationPlural: 'Facilities',
    enrollment: 'Registration',
    graduation: 'Discharge',
    term: 'Fiscal Year',
    photography: 'Brand Photography',
    storyBank: 'Patient Stories',
    factBook: 'Quality Metrics',
    industryContext: 'healthcare system communications',
    contentStyle: 'patient-centered healthcare communications',
  },
  audiences: [
    { id: 'prospective-patient', label: 'Prospective Patient', description: 'Potential new patient' },
    { id: 'current-patient', label: 'Current Patient', description: 'Active patient in care' },
    { id: 'caregiver', label: 'Caregiver / Family', description: 'Patient family and caregivers' },
    { id: 'referring-physician', label: 'Referring Physician', description: 'External referring providers' },
    { id: 'employee', label: 'Staff', description: 'Clinical and administrative staff' },
    { id: 'community', label: 'Community', description: 'Local community audience' },
    { id: 'donor', label: 'Donor / Foundation', description: 'Philanthropic supporters' },
    { id: 'general', label: 'General', description: 'Broad public health audience' },
  ],
  cohorts: [
    { id: 'new-patient', label: 'New Patient', audienceIds: ['prospective-patient', 'current-patient'] },
    { id: 'chronic-care', label: 'Chronic Care', audienceIds: ['current-patient'] },
    { id: 'post-surgical', label: 'Post-Surgical', audienceIds: ['current-patient'] },
    { id: 'wellness', label: 'Wellness Program', audienceIds: ['current-patient', 'community'] },
    { id: 'pediatric-family', label: 'Pediatric Family', audienceIds: ['caregiver'] },
    { id: 'none', label: 'No specific segment', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Brand Awareness', description: 'Health system awareness', category: 'Marketing' },
    { id: 'patient-acquisition', label: 'Patient Acquisition', description: 'New patient outreach', category: 'Growth' },
    { id: 'appointment-reminder', label: 'Appointment Reminder', description: 'Appointment confirmations', category: 'Operations' },
    { id: 'post-visit', label: 'Post-Visit Follow-Up', description: 'After-visit care instructions', category: 'Clinical' },
    { id: 'wellness-campaign', label: 'Wellness Campaign', description: 'Preventive health outreach', category: 'Community' },
    { id: 'service-line-launch', label: 'Service Line Launch', description: 'New service or facility opening', category: 'Marketing' },
    { id: 'patient-satisfaction', label: 'Patient Satisfaction', description: 'Survey and feedback requests', category: 'Quality' },
    { id: 'community-health', label: 'Community Health Event', description: 'Health fairs and screenings', category: 'Community' },
    { id: 'internal-comms', label: 'Internal Communications', description: 'Staff announcements', category: 'Internal' },
    { id: 'crisis-comms', label: 'Crisis Communications', description: 'Public health emergency', category: 'Operations' },
  ],
  domains: [
    { id: 'clinical', label: 'Clinical Care', description: 'Patient care and treatment' },
    { id: 'marketing', label: 'Marketing', description: 'Patient acquisition and brand' },
    { id: 'quality', label: 'Quality & Safety', description: 'Patient safety and outcomes' },
    { id: 'community-health', label: 'Community Health', description: 'Public and community health' },
    { id: 'operations', label: 'Operations', description: 'Facilities and administration' },
    { id: 'hr-culture', label: 'HR & Culture', description: 'Staff recruitment and culture' },
    { id: 'philanthropy', label: 'Philanthropy', description: 'Foundation and donor relations' },
    { id: 'compliance', label: 'Compliance', description: 'HIPAA, regulatory, and legal' },
  ],
  goals: [
    { id: 'schedule', label: 'Schedule', description: 'Book an appointment' },
    { id: 'register', label: 'Register', description: 'Complete patient registration' },
    { id: 'comply', label: 'Comply', description: 'Follow care instructions' },
    { id: 'attend', label: 'Attend', description: 'Attend appointment or event' },
    { id: 'respond', label: 'Respond', description: 'Complete survey or form' },
    { id: 'donate', label: 'Donate', description: 'Support the foundation' },
    { id: 'refer', label: 'Refer', description: 'Refer a patient or provider' },
    { id: 'engage', label: 'Engage', description: 'Participate in wellness program' },
  ],
  departments: [
    { id: 'marketing', label: 'Marketing', description: 'Brand and patient acquisition', icon: 'megaphone' },
    { id: 'patient-experience', label: 'Patient Experience', description: 'Patient satisfaction and engagement', icon: 'heart' },
    { id: 'clinical-ops', label: 'Clinical Operations', description: 'Care delivery management', icon: 'stethoscope' },
    { id: 'community-health', label: 'Community Health', description: 'Outreach and prevention', icon: 'users' },
    { id: 'foundation', label: 'Foundation', description: 'Philanthropy and fundraising', icon: 'heart-pulse' },
    { id: 'hr', label: 'Human Resources', description: 'Staff recruitment and retention', icon: 'briefcase' },
    { id: 'executive', label: 'Executive Office', description: 'Leadership communications', icon: 'building-2' },
  ],
  storyTypes: [
    { id: 'patient', label: 'Patient', icon: 'Heart' },
    { id: 'provider', label: 'Provider', icon: 'Stethoscope' },
    { id: 'staff', label: 'Staff', icon: 'Users' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'innovation', label: 'Innovation', icon: 'Lightbulb' },
    { id: 'donor', label: 'Donor', icon: 'Gift' },
  ],
  relevantConfigFields: [
    'institutionName', 'slogans', 'emailDomain',
    'primaryCTAs', 'primaryContactEmail', 'primaryContactPhone',
    'websiteLinks', 'socialMediaHandles',
    'toneRules', 'wordsToAvoid', 'preferredPhrases',
  ],
  classificationOptions: [
    { value: 'hospital-system', label: 'Hospital System', description: 'Multi-hospital health system' },
    { value: 'physician-group', label: 'Physician Group', description: 'Multi-specialty physician practice' },
    { value: 'community-hospital', label: 'Community Hospital', description: 'Single community hospital' },
    { value: 'specialty-clinic', label: 'Specialty Clinic', description: 'Focused specialty practice' },
    { value: 'health-plan', label: 'Health Plan / Insurance', description: 'Health insurance or managed care' },
  ],
};
