import type { IndustryVocabulary } from '@/types/industry';

export const higherEdVocabulary: IndustryVocabulary = {
  tenantType: 'university',
  labels: {
    organization: 'University',
    organizationShort: 'Univ.',
    organizationPlural: 'Universities',
    organizationSettings: 'University Settings',
    organizationAdmin: 'University Admin',
    organizationUser: 'University User',
    primaryAudience: 'Students',
    primaryAudienceSingular: 'Student',
    supporter: 'Donor',
    alumnus: 'Alumnus',
    alumniPlural: 'Alumni',
    staff: 'Faculty & Staff',
    leader: 'President',
    leaderTitle: 'President',
    subUnit: 'College/School',
    subUnitPlural: 'Colleges & Schools',
    location: 'Campus',
    locationPlural: 'Campuses',
    enrollment: 'Enrollment',
    graduation: 'Graduation',
    term: 'Semester',
    photography: 'Campus Photography',
    storyBank: 'Story Bank',
    factBook: 'Fact Book',
    industryContext: 'higher education',
    contentStyle: 'institutional communications',
  },
  audiences: [
    { id: 'prospective', label: 'Prospective Student', description: 'Students considering enrollment' },
    { id: 'first-year', label: 'First-Year Student', description: 'Newly enrolled students' },
    { id: 'continuing', label: 'Continuing Student', description: 'Currently enrolled returning students' },
    { id: 'at-risk', label: 'At-Risk Student', description: 'Students at risk of stopping out' },
    { id: 'graduate', label: 'Graduate Student', description: 'Masters and doctoral students' },
    { id: 'online-learner', label: 'Online Learner', description: 'Students in online programs' },
    { id: 'employee', label: 'Employee', description: 'Faculty and staff members' },
    { id: 'alumni', label: 'Alumni', description: 'Graduates of the institution' },
    { id: 'parents', label: 'Parents & Families', description: 'Parents and family members of students' },
    { id: 'donors', label: 'Donors', description: 'Financial supporters' },
    { id: 'policy-makers', label: 'Policy Makers', description: 'Government and regulatory officials' },
    { id: 'community-partners', label: 'Community Partners', description: 'Local organizations and partners' },
    { id: 'higher-ed-leaders', label: 'Higher Ed Leaders', description: 'Peer institution leaders' },
    { id: 'general', label: 'General', description: 'Broad institutional audience' },
  ],
  cohorts: [
    { id: 'first-gen', label: 'First-Generation', audienceIds: ['prospective', 'first-year', 'continuing'] },
    { id: 'probation', label: 'Academic Probation', audienceIds: ['continuing', 'at-risk'] },
    { id: 'online', label: 'Online Only', audienceIds: ['prospective', 'continuing', 'online-learner'] },
    { id: 'commuter', label: 'Commuter', audienceIds: ['first-year', 'continuing'] },
    { id: 'residential', label: 'Residential', audienceIds: ['first-year', 'continuing'] },
    { id: 'transfer', label: 'Transfer', audienceIds: ['prospective', 'first-year'] },
    { id: 'international', label: 'International', audienceIds: ['prospective', 'first-year', 'continuing', 'graduate'] },
    { id: 'veteran', label: 'Veteran', audienceIds: ['prospective', 'first-year', 'continuing'] },
    { id: 'working-adult', label: 'Working Adult', audienceIds: ['prospective', 'continuing', 'online-learner'] },
    { id: 'faculty', label: 'Faculty', audienceIds: ['employee'] },
    { id: 'staff', label: 'Staff', audienceIds: ['employee'] },
    { id: 'young-alumni', label: 'Young Alumni', audienceIds: ['alumni'] },
    { id: 'lapsed-alumni', label: 'Lapsed Alumni', audienceIds: ['alumni'] },
    { id: 'first-time-donor', label: 'First-Time Donor', audienceIds: ['donors'] },
    { id: 'major-gift-prospect', label: 'Major Gift Prospect', audienceIds: ['donors'] },
    { id: 'lapsed-donor', label: 'Lapsed Donor', audienceIds: ['donors'] },
    { id: 'prospective-parent', label: 'Prospective Parent', audienceIds: ['parents'] },
    { id: 'current-parent', label: 'Current Parent', audienceIds: ['parents'] },
    { id: 'none', label: 'No specific cohort', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Brand Awareness', description: 'General awareness campaigns', category: 'General' },
    { id: 'recruitment', label: 'Recruitment', description: 'Student recruitment outreach', category: 'Student' },
    { id: 'orientation', label: 'Orientation', description: 'New student orientation', category: 'Student' },
    { id: 'registration', label: 'Registration', description: 'Course registration period', category: 'Student' },
    { id: 'early-term', label: 'Early Term', description: 'Start of semester communications', category: 'Student' },
    { id: 'midterm', label: 'Midterm', description: 'Mid-semester check-in', category: 'Student' },
    { id: 'finals', label: 'Finals', description: 'End of semester support', category: 'Student' },
    { id: 'yield', label: 'Yield', description: 'Converting admitted to enrolled', category: 'Student' },
    { id: 'summer-melt', label: 'Summer Melt', description: 'Preventing enrollment loss over summer', category: 'Student' },
    { id: 're-engagement', label: 'Re-Engagement', description: 'Reaching out to disengaged', category: 'Student' },
    { id: 'graduation', label: 'Graduation', description: 'Commencement communications', category: 'Student' },
    { id: 'giving-day', label: 'Giving Day', description: 'Annual giving day campaigns', category: 'Advancement' },
    { id: 'annual-fund', label: 'Annual Fund', description: 'Annual fundraising campaign', category: 'Advancement' },
    { id: 'stewardship', label: 'Stewardship', description: 'Donor stewardship and thanks', category: 'Advancement' },
    { id: 'homecoming', label: 'Homecoming', description: 'Homecoming event promotion', category: 'Alumni' },
    { id: 'reunion-campaign', label: 'Reunion', description: 'Class reunion outreach', category: 'Alumni' },
    { id: 'open-enrollment', label: 'Open Enrollment', description: 'Benefits enrollment period', category: 'Employee' },
    { id: 'campus-event', label: 'Campus Event', description: 'Campus event promotion', category: 'General' },
  ],
  domains: [
    { id: 'academic', label: 'Academic', description: 'Coursework, advising, academic support' },
    { id: 'financial', label: 'Financial Aid', description: 'Financial aid, tuition, billing' },
    { id: 'admissions', label: 'Admissions', description: 'Application and admission process' },
    { id: 'recruitment', label: 'Recruitment', description: 'Student recruitment outreach' },
    { id: 'engagement', label: 'Student Engagement', description: 'Campus life and involvement' },
    { id: 'wellbeing', label: 'Wellbeing', description: 'Mental health, wellness, safety' },
    { id: 'giving', label: 'Advancement & Giving', description: 'Fundraising and donor relations' },
    { id: 'alumni-relations', label: 'Alumni Relations', description: 'Alumni engagement and events' },
    { id: 'hr-benefits', label: 'HR & Benefits', description: 'Employee benefits and HR' },
    { id: 'operations', label: 'Operations', description: 'Facilities, IT, campus operations' },
    { id: 'compliance', label: 'Compliance', description: 'Regulatory and policy compliance' },
  ],
  goals: [
    { id: 'enroll', label: 'Enroll', description: 'Drive enrollment or registration' },
    { id: 'persist', label: 'Persist', description: 'Support student retention' },
    { id: 'attend', label: 'Attend', description: 'Drive event attendance' },
    { id: 'submit', label: 'Submit', description: 'Complete a form or application' },
    { id: 'respond', label: 'Respond', description: 'Reply or take action' },
    { id: 'register', label: 'Register', description: 'Register for courses or events' },
    { id: 'donate', label: 'Donate', description: 'Make a financial contribution' },
    { id: 'engage', label: 'Engage', description: 'Participate in community' },
    { id: 'apply', label: 'Apply', description: 'Submit an application' },
    { id: 'yield', label: 'Yield', description: 'Confirm enrollment decision' },
    { id: 'acknowledge', label: 'Acknowledge', description: 'Read and confirm receipt' },
  ],
  departments: [
    { id: 'central-marketing', label: 'Central Marketing', description: 'University marketing and communications' },
    { id: 'enrollment-management', label: 'Enrollment Management', description: 'Admissions and enrollment' },
    { id: 'student-success', label: 'Student Success', description: 'Retention and advising' },
    { id: 'advancement-alumni', label: 'Advancement & Alumni', description: 'Fundraising and alumni relations' },
    { id: 'executive-comms', label: 'Executive Communications', description: 'President and leadership office' },
    { id: 'college-communications', label: 'College Communications', description: 'Individual college marketing' },
    { id: 'human-resources', label: 'Human Resources', description: 'HR and employee communications' },
    { id: 'registrar', label: 'Registrar', description: 'Academic records and registration' },
  ],
  storyTypes: [
    { id: 'student', label: 'Student', icon: 'GraduationCap' },
    { id: 'alumni', label: 'Alumni', icon: 'Users' },
    { id: 'donor', label: 'Donor', icon: 'Heart' },
    { id: 'faculty', label: 'Faculty', icon: 'Briefcase' },
    { id: 'staff', label: 'Staff', icon: 'User' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'institutional', label: 'Institutional', icon: 'Building2' },
  ],
  relevantConfigFields: [
    'institutionType', 'institutionName', 'mascot', 'slogans',
    'portalName', 'lmsName', 'emailDomain',
    'academicTerms', 'gradingTerms', 'enrollmentTerms',
    'campusTerms', 'registrarOffice', 'admissionsOffice', 'financialAidOffice',
    'studentAddressing', 'staffAddressing',
    'presidentName', 'provostName', 'deanName',
  ],
  classificationOptions: [
    { value: 'doctoral-university', label: 'Doctoral University', description: 'Research-intensive university offering doctoral degrees' },
    { value: 'masters-university', label: "Master's University", description: "University offering master's as highest degree" },
    { value: 'baccalaureate-college', label: 'Baccalaureate College', description: "Four-year college focused on bachelor's degrees" },
    { value: 'associates-college', label: "Associate's College", description: 'Community or two-year college' },
    { value: 'special-focus', label: 'Special Focus', description: 'Specialized institution (art, law, medical, etc.)' },
  ],
};
