import type { IndustryVocabulary } from '@/types/industry';

export const nonprofitVocabulary: IndustryVocabulary = {
  tenantType: 'nonprofit',
  labels: {
    organization: 'Organization',
    organizationShort: 'Org.',
    organizationPlural: 'Organizations',
    organizationSettings: 'Organization Settings',
    organizationAdmin: 'Organization Admin',
    organizationUser: 'Team Member',
    primaryAudience: 'Supporters',
    primaryAudienceSingular: 'Supporter',
    supporter: 'Donor',
    alumnus: 'Past Volunteer',
    alumniPlural: 'Past Volunteers',
    staff: 'Staff & Volunteers',
    leader: 'Executive Director',
    leaderTitle: 'Executive Director',
    subUnit: 'Chapter',
    subUnitPlural: 'Chapters',
    location: 'Office',
    locationPlural: 'Offices',
    enrollment: 'Sign-Up',
    graduation: 'Completion',
    term: 'Fiscal Year',
    photography: 'Impact Photography',
    storyBank: 'Impact Stories',
    factBook: 'Impact Metrics',
    industryContext: 'nonprofit and mission-driven organization',
    contentStyle: 'mission-driven donor and community communications',
  },
  audiences: [
    { id: 'potential-donor', label: 'Potential Donor', description: 'Prospective financial supporter' },
    { id: 'active-donor', label: 'Active Donor', description: 'Current recurring or recent donor' },
    { id: 'major-donor', label: 'Major Donor', description: 'High-capacity donor or foundation' },
    { id: 'lapsed-donor', label: 'Lapsed Donor', description: 'Previously gave, now inactive' },
    { id: 'volunteer', label: 'Volunteer', description: 'Active volunteer contributor' },
    { id: 'prospect-volunteer', label: 'Prospective Volunteer', description: 'Interested in volunteering' },
    { id: 'beneficiary', label: 'Beneficiary', description: 'People served by the organization' },
    { id: 'board-member', label: 'Board Member', description: 'Board of directors' },
    { id: 'corporate-partner', label: 'Corporate Partner', description: 'Corporate sponsors and partners' },
    { id: 'advocate', label: 'Advocate', description: 'Policy and awareness advocates' },
    { id: 'chapter-leader', label: 'Chapter Leader', description: 'Local chapter or affiliate leader' },
    { id: 'employee', label: 'Staff', description: 'Organization employees' },
    { id: 'general', label: 'General Public', description: 'Broad awareness audience' },
  ],
  cohorts: [
    { id: 'first-time-donor', label: 'First-Time Donor', audienceIds: ['potential-donor', 'active-donor'] },
    { id: 'monthly-giver', label: 'Monthly Giver', audienceIds: ['active-donor'] },
    { id: 'event-attendee', label: 'Event Attendee', audienceIds: ['potential-donor', 'active-donor', 'volunteer'] },
    { id: 'peer-fundraiser', label: 'Peer Fundraiser', audienceIds: ['active-donor', 'volunteer'] },
    { id: 'corporate-match', label: 'Corporate Match Eligible', audienceIds: ['active-donor'] },
    { id: 'legacy-society', label: 'Legacy Society', audienceIds: ['major-donor'] },
    { id: 'young-professional', label: 'Young Professional', audienceIds: ['potential-donor', 'volunteer'] },
    { id: 'none', label: 'No specific segment', audienceIds: [] },
  ],
  moments: [
    { id: 'brand-awareness', label: 'Awareness Campaign', description: 'Mission awareness outreach', category: 'Awareness' },
    { id: 'annual-appeal', label: 'Annual Appeal', description: 'Year-end or annual fundraising', category: 'Fundraising' },
    { id: 'giving-tuesday', label: 'Giving Tuesday', description: 'Giving Tuesday campaign', category: 'Fundraising' },
    { id: 'gala-event', label: 'Gala / Fundraiser', description: 'Major fundraising event', category: 'Events' },
    { id: 'impact-report', label: 'Impact Report', description: 'Annual or quarterly impact sharing', category: 'Stewardship' },
    { id: 'stewardship', label: 'Donor Stewardship', description: 'Thank you and recognition', category: 'Stewardship' },
    { id: 'volunteer-recruitment', label: 'Volunteer Recruitment', description: 'Volunteer drive', category: 'Engagement' },
    { id: 'advocacy-action', label: 'Advocacy Action', description: 'Call to action on policy', category: 'Advocacy' },
    { id: 'emergency-appeal', label: 'Emergency Appeal', description: 'Urgent disaster or crisis response', category: 'Fundraising' },
    { id: 'new-member-welcome', label: 'New Member Welcome', description: 'Onboarding new supporters', category: 'Engagement' },
    { id: 'chapter-activation', label: 'Chapter Activation', description: 'Local chapter engagement', category: 'Engagement' },
    { id: 'internal-comms', label: 'Internal Communications', description: 'Staff and board updates', category: 'Internal' },
  ],
  domains: [
    { id: 'fundraising', label: 'Fundraising', description: 'Donor cultivation and solicitation' },
    { id: 'stewardship', label: 'Stewardship', description: 'Donor recognition and retention' },
    { id: 'programs', label: 'Programs & Impact', description: 'Program outcomes and beneficiary stories' },
    { id: 'advocacy', label: 'Advocacy', description: 'Policy, awareness, and action campaigns' },
    { id: 'volunteer-mgmt', label: 'Volunteer Management', description: 'Volunteer recruitment and coordination' },
    { id: 'events', label: 'Events', description: 'Event planning and promotion' },
    { id: 'marketing', label: 'Marketing & Comms', description: 'Brand awareness and content' },
    { id: 'operations', label: 'Operations', description: 'Internal operations and board governance' },
  ],
  goals: [
    { id: 'donate', label: 'Donate', description: 'Make a financial gift' },
    { id: 'volunteer', label: 'Volunteer', description: 'Sign up to volunteer' },
    { id: 'attend', label: 'Attend', description: 'Attend an event or briefing' },
    { id: 'advocate', label: 'Advocate', description: 'Take action on a cause' },
    { id: 'share', label: 'Share', description: 'Amplify the message' },
    { id: 'register', label: 'Register', description: 'Sign up for program or event' },
    { id: 'renew-giving', label: 'Renew Giving', description: 'Renew lapsed donation' },
    { id: 'upgrade-giving', label: 'Upgrade Gift', description: 'Increase giving level' },
    { id: 'engage', label: 'Engage', description: 'Participate in community' },
    { id: 'respond', label: 'Respond', description: 'Reply to survey or request' },
  ],
  departments: [
    { id: 'development', label: 'Development', description: 'Fundraising and donor relations' },
    { id: 'programs', label: 'Programs', description: 'Program delivery and impact' },
    { id: 'marketing-comms', label: 'Marketing & Comms', description: 'Brand and communications' },
    { id: 'advocacy', label: 'Advocacy', description: 'Policy and advocacy' },
    { id: 'volunteer-services', label: 'Volunteer Services', description: 'Volunteer coordination' },
    { id: 'executive', label: 'Executive Office', description: 'ED and leadership team' },
    { id: 'operations', label: 'Operations', description: 'Finance, HR, admin' },
  ],
  storyTypes: [
    { id: 'beneficiary', label: 'Beneficiary', icon: 'Heart' },
    { id: 'donor', label: 'Donor', icon: 'Gift' },
    { id: 'volunteer', label: 'Volunteer', icon: 'HandHeart' },
    { id: 'staff', label: 'Staff', icon: 'Users' },
    { id: 'community', label: 'Community', icon: 'Globe' },
    { id: 'impact', label: 'Impact', icon: 'TrendingUp' },
  ],
  relevantConfigFields: [
    'institutionName', 'slogans', 'emailDomain',
    'primaryCTAs', 'secondaryCTAs', 'urgentCTAs',
    'primaryContactEmail', 'primaryContactPhone',
    'websiteLinks', 'socialMediaHandles',
    'toneRules', 'wordsToAvoid', 'preferredPhrases',
  ],
  classificationOptions: [
    { value: 'national-nonprofit', label: 'National Nonprofit', description: 'National organization with chapters or affiliates' },
    { value: 'international-ngo', label: 'International NGO', description: 'Global nongovernmental organization' },
    { value: 'community-foundation', label: 'Community Foundation', description: 'Local or regional foundation' },
    { value: 'advocacy-org', label: 'Advocacy Organization', description: 'Policy and cause-focused organization' },
    { value: 'faith-based', label: 'Faith-Based Organization', description: 'Religious or spiritual mission' },
    { value: 'membership-org', label: 'Membership Organization', description: 'Dues-based professional or civic association' },
  ],
};
