/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EmbedRouteImport } from './routes/_embed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CopywriterPopoutRouteImport } from './routes/copywriter-popout'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as ForAgenciesRouteImport } from './routes/for-agencies'
import { Route as ForEnterpriseRouteImport } from './routes/for-enterprise'
import { Route as HigherEducationMarketingStrategiesRouteImport } from './routes/higher-education-marketing-strategies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OgPreviewRouteImport } from './routes/og-preview'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TryCopywriterRouteImport } from './routes/try-copywriter'
import { Route as AppAdminRouteImport } from './routes/_app/_admin'
import { Route as AppSuperadminRouteImport } from './routes/_app/_superadmin'
import { Route as AppAccessibilityRouteImport } from './routes/_app/accessibility'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppBenchmarksRouteImport } from './routes/_app/benchmarks'
import { Route as AppBrandAuditRouteImport } from './routes/_app/brand-audit'
import { Route as AppBrandStudioRouteImport } from './routes/_app/brand-studio'
import { Route as AppBrandVoiceRouteImport } from './routes/_app/brand-voice'
import { Route as AppBuildRouteImport } from './routes/_app/build'
import { Route as AppByocRouteImport } from './routes/_app/byoc'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppCallScriptRouteImport } from './routes/_app/call-script'
import { Route as AppCampaignBriefRouteImport } from './routes/_app/campaign-brief'
import { Route as AppCampaignDashboardRouteImport } from './routes/_app/campaign-dashboard'
import { Route as AppCompetitiveAnalyzerRouteImport } from './routes/_app/competitive-analyzer'
import { Route as AppContentDnaRouteImport } from './routes/_app/content-dna'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppEmailPreviewRouteImport } from './routes/_app/email-preview'
import { Route as AppEvaluateRouteImport } from './routes/_app/evaluate'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppGivingDayPlannerRouteImport } from './routes/_app/giving-day-planner'
import { Route as AppImageGeneratorRouteImport } from './routes/_app/image-generator'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppOrganizationSettingsRouteImport } from './routes/_app/organization-settings'
import { Route as AppPlaygroundRouteImport } from './routes/_app/playground'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppRegionAdapterRouteImport } from './routes/_app/region-adapter'
import { Route as AppRegionalPlaybookRouteImport } from './routes/_app/regional-playbook'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSocialPostsRouteImport } from './routes/_app/social-posts'
import { Route as AppStewardshipReportRouteImport } from './routes/_app/stewardship-report'
import { Route as AppStrategyRouteImport } from './routes/_app/strategy'
import { Route as AppSubjectOptimizerRouteImport } from './routes/_app/subject-optimizer'
import { Route as AppToolsRouteImport } from './routes/_app/tools'
import { Route as AppTranslateRouteImport } from './routes/_app/translate'
import { Route as AppUniversitySettingsRouteImport } from './routes/_app/university-settings'
import { Route as AppWebAnalyzerRouteImport } from './routes/_app/web-analyzer'
import { Route as AgencyRequestAccessRouteImport } from './routes/agency.request-access'
import { Route as CompassIndexRouteImport } from './routes/compass/index'
import { Route as CompassLockerRouteImport } from './routes/compass/locker'
import { Route as CompassSetupRouteImport } from './routes/compass/setup'
import { Route as DocsSalesforceCanvasRouteImport } from './routes/docs/salesforce-canvas'
import { Route as FeaturesIndexRouteImport } from './routes/features/index'
import { Route as FeaturesAiCopywriterRouteImport } from './routes/features/ai-copywriter'
import { Route as FeaturesBrandAuditRouteImport } from './routes/features/brand-audit'
import { Route as FeaturesBrandStudioRouteImport } from './routes/features/brand-studio'
import { Route as FeaturesContentDnaRouteImport } from './routes/features/content-dna'
import { Route as FeaturesEvaluateRouteImport } from './routes/features/evaluate'
import { Route as FeaturesImageStudioRouteImport } from './routes/features/image-studio'
import { Route as FeaturesJourneyDesignerRouteImport } from './routes/features/journey-designer'
import { Route as FeaturesLibraryRouteImport } from './routes/features/library'
import { Route as FeaturesMessageBuilderRouteImport } from './routes/features/message-builder'
import { Route as FeaturesWebcrawlRouteImport } from './routes/features/webcrawl'
import { Route as IntegrationsSalesforceCanvasRouteImport } from './routes/integrations/salesforce-canvas'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppAdminInstitutionDashboardRouteImport } from './routes/_app/_admin/institution-dashboard'
import { Route as AppSuperadminPlatformRouteImport } from './routes/_app/_superadmin/platform'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin.index'
import { Route as AppAgencyAnalyticsRouteImport } from './routes/_app/agency.analytics'
import { Route as AppAgencyClientsRouteImport } from './routes/_app/agency.clients'
import { Route as AppAgencyDashboardRouteImport } from './routes/_app/agency.dashboard'
import { Route as AppAgencyOnboardingRouteImport } from './routes/_app/agency.onboarding'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections.$id'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library.index'
import { Route as AppLibraryIdRouteImport } from './routes/_app/library.$id'
import { Route as AppSharedLibraryIndexRouteImport } from './routes/_app/shared-library.index'
import { Route as AppSharedLibraryIdRouteImport } from './routes/_app/shared-library.$id'
import { Route as EmbedEmbedBrandAuditRouteImport } from './routes/_embed/embed.brand-audit'
import { Route as EmbedEmbedBrandStudioRouteImport } from './routes/_embed/embed.brand-studio'
import { Route as EmbedEmbedBrandVoiceRouteImport } from './routes/_embed/embed.brand-voice'
import { Route as EmbedEmbedBuildRouteImport } from './routes/_embed/embed.build'
import { Route as EmbedEmbedCampaignBriefRouteImport } from './routes/_embed/embed.campaign-brief'
import { Route as EmbedEmbedCompetitiveAnalyzerRouteImport } from './routes/_embed/embed.competitive-analyzer'
import { Route as EmbedEmbedEvaluateRouteImport } from './routes/_embed/embed.evaluate'
import { Route as EmbedEmbedImageGeneratorRouteImport } from './routes/_embed/embed.image-generator'
import { Route as EmbedEmbedPlaygroundRouteImport } from './routes/_embed/embed.playground'
import { Route as EmbedEmbedRegionAdapterRouteImport } from './routes/_embed/embed.region-adapter'
import { Route as EmbedEmbedRegionalPlaybookRouteImport } from './routes/_embed/embed.regional-playbook'
import { Route as EmbedEmbedSubjectOptimizerRouteImport } from './routes/_embed/embed.subject-optimizer'
import { Route as EmbedEmbedTranslateRouteImport } from './routes/_embed/embed.translate'
import { Route as EmbedEmbedWebAnalyzerRouteImport } from './routes/_embed/embed.web-analyzer'
import { Route as NdaSignSlugRouteImport } from './routes/nda/sign/$slug'
import { Route as AppAdminAdminConsoleRouteImport } from './routes/_app/_admin/admin.console'
import { Route as AppAdminAdminContentDnaRouteImport } from './routes/_app/_admin/admin.content-dna'
import { Route as AppAdminAdminUsersRouteImport } from './routes/_app/_admin/admin.users'
import { Route as AppSuperadminAdminAiTechnologyRouteImport } from './routes/_app/_superadmin/admin.ai-technology'
import { Route as AppSuperadminAdminCompassUsersRouteImport } from './routes/_app/_superadmin/admin.compass-users'
import { Route as AppSuperadminAdminCrmRouteImport } from './routes/_app/_superadmin/admin.crm'
import { Route as AppSuperadminAdminLockerRouteImport } from './routes/_app/_superadmin/admin.locker'
import { Route as AppSuperadminAdminNdaLinksRouteImport } from './routes/_app/_superadmin/admin.nda-links'
import { Route as AppSuperadminAdminPanelRouteImport } from './routes/_app/_superadmin/admin.panel'
import { Route as AppSuperadminAdminProspectOutreachRouteImport } from './routes/_app/_superadmin/admin.prospect-outreach'
import { Route as AppSuperadminAdminQaRouteImport } from './routes/_app/_superadmin/admin.qa'
import { Route as AppSuperadminAdminSecurityEventsRouteImport } from './routes/_app/_superadmin/admin.security-events'
import { Route as AppSuperadminAdminSeedRouteImport } from './routes/_app/_superadmin/admin.seed'
import { Route as AppAdminPersonalAiIndexRouteImport } from './routes/_app/admin.personal-ai.index'
import { Route as AppSuperadminAdminInstitutionIdRouteImport } from './routes/_app/_superadmin/admin.institution.$id'
import { Route as AppSuperadminAdminPersonalAiEditsRouteImport } from './routes/_app/_superadmin/admin.personal-ai.edits'
import { Route as AppSuperadminAdminUserIdRouteImport } from './routes/_app/_superadmin/admin.user.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/_embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CopywriterPopoutRoute = CopywriterPopoutRouteImport.update({
  id: '/copywriter-popout',
  path: '/copywriter-popout',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const ForAgenciesRoute = ForAgenciesRouteImport.update({
  id: '/for-agencies',
  path: '/for-agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEnterpriseRoute = ForEnterpriseRouteImport.update({
  id: '/for-enterprise',
  path: '/for-enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const HigherEducationMarketingStrategiesRoute =
  HigherEducationMarketingStrategiesRouteImport.update({
    id: '/higher-education-marketing-strategies',
    path: '/higher-education-marketing-strategies',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OgPreviewRoute = OgPreviewRouteImport.update({
  id: '/og-preview',
  path: '/og-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TryCopywriterRoute = TryCopywriterRouteImport.update({
  id: '/try-copywriter',
  path: '/try-copywriter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminRoute = AppSuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessibilityRoute = AppAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppBenchmarksRoute = AppBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandAuditRoute = AppBrandAuditRouteImport.update({
  id: '/brand-audit',
  path: '/brand-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandStudioRoute = AppBrandStudioRouteImport.update({
  id: '/brand-studio',
  path: '/brand-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandVoiceRoute = AppBrandVoiceRouteImport.update({
  id: '/brand-voice',
  path: '/brand-voice',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildRoute = AppBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => AppRoute,
} as any)
const AppByocRoute = AppByocRouteImport.update({
  id: '/byoc',
  path: '/byoc',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCallScriptRoute = AppCallScriptRouteImport.update({
  id: '/call-script',
  path: '/call-script',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignBriefRoute = AppCampaignBriefRouteImport.update({
  id: '/campaign-brief',
  path: '/campaign-brief',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignDashboardRoute = AppCampaignDashboardRouteImport.update({
  id: '/campaign-dashboard',
  path: '/campaign-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitiveAnalyzerRoute = AppCompetitiveAnalyzerRouteImport.update({
  id: '/competitive-analyzer',
  path: '/competitive-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppContentDnaRoute = AppContentDnaRouteImport.update({
  id: '/content-dna',
  path: '/content-dna',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailPreviewRoute = AppEmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => AppRoute,
} as any)
const AppEvaluateRoute = AppEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppGivingDayPlannerRoute = AppGivingDayPlannerRouteImport.update({
  id: '/giving-day-planner',
  path: '/giving-day-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppImageGeneratorRoute = AppImageGeneratorRouteImport.update({
  id: '/image-generator',
  path: '/image-generator',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationSettingsRoute = AppOrganizationSettingsRouteImport.update({
  id: '/organization-settings',
  path: '/organization-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRegionAdapterRoute = AppRegionAdapterRouteImport.update({
  id: '/region-adapter',
  path: '/region-adapter',
  getParentRoute: () => AppRoute,
} as any)
const AppRegionalPlaybookRoute = AppRegionalPlaybookRouteImport.update({
  id: '/regional-playbook',
  path: '/regional-playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialPostsRoute = AppSocialPostsRouteImport.update({
  id: '/social-posts',
  path: '/social-posts',
  getParentRoute: () => AppRoute,
} as any)
const AppStewardshipReportRoute = AppStewardshipReportRouteImport.update({
  id: '/stewardship-report',
  path: '/stewardship-report',
  getParentRoute: () => AppRoute,
} as any)
const AppStrategyRoute = AppStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectOptimizerRoute = AppSubjectOptimizerRouteImport.update({
  id: '/subject-optimizer',
  path: '/subject-optimizer',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppTranslateRoute = AppTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AppRoute,
} as any)
const AppUniversitySettingsRoute = AppUniversitySettingsRouteImport.update({
  id: '/university-settings',
  path: '/university-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWebAnalyzerRoute = AppWebAnalyzerRouteImport.update({
  id: '/web-analyzer',
  path: '/web-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AgencyRequestAccessRoute = AgencyRequestAccessRouteImport.update({
  id: '/agency/request-access',
  path: '/agency/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassIndexRoute = CompassIndexRouteImport.update({
  id: '/compass/',
  path: '/compass/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassLockerRoute = CompassLockerRouteImport.update({
  id: '/compass/locker',
  path: '/compass/locker',
  getParentRoute: () => rootRouteImport,
} as any)
const CompassSetupRoute = CompassSetupRouteImport.update({
  id: '/compass/setup',
  path: '/compass/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSalesforceCanvasRoute = DocsSalesforceCanvasRouteImport.update({
  id: '/docs/salesforce-canvas',
  path: '/docs/salesforce-canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAiCopywriterRoute = FeaturesAiCopywriterRouteImport.update({
  id: '/features/ai-copywriter',
  path: '/features/ai-copywriter',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesBrandAuditRoute = FeaturesBrandAuditRouteImport.update({
  id: '/features/brand-audit',
  path: '/features/brand-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesBrandStudioRoute = FeaturesBrandStudioRouteImport.update({
  id: '/features/brand-studio',
  path: '/features/brand-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesContentDnaRoute = FeaturesContentDnaRouteImport.update({
  id: '/features/content-dna',
  path: '/features/content-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesEvaluateRoute = FeaturesEvaluateRouteImport.update({
  id: '/features/evaluate',
  path: '/features/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesImageStudioRoute = FeaturesImageStudioRouteImport.update({
  id: '/features/image-studio',
  path: '/features/image-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesJourneyDesignerRoute = FeaturesJourneyDesignerRouteImport.update({
  id: '/features/journey-designer',
  path: '/features/journey-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesLibraryRoute = FeaturesLibraryRouteImport.update({
  id: '/features/library',
  path: '/features/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesMessageBuilderRoute = FeaturesMessageBuilderRouteImport.update({
  id: '/features/message-builder',
  path: '/features/message-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesWebcrawlRoute = FeaturesWebcrawlRouteImport.update({
  id: '/features/webcrawl',
  path: '/features/webcrawl',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSalesforceCanvasRoute =
  IntegrationsSalesforceCanvasRouteImport.update({
    id: '/integrations/salesforce-canvas',
    path: '/integrations/salesforce-canvas',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminInstitutionDashboardRoute =
  AppAdminInstitutionDashboardRouteImport.update({
    id: '/institution-dashboard',
    path: '/institution-dashboard',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppSuperadminPlatformRoute = AppSuperadminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyAnalyticsRoute = AppAgencyAnalyticsRouteImport.update({
  id: '/agency/analytics',
  path: '/agency/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyClientsRoute = AppAgencyClientsRouteImport.update({
  id: '/agency/clients',
  path: '/agency/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyDashboardRoute = AppAgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgencyOnboardingRoute = AppAgencyOnboardingRouteImport.update({
  id: '/agency/onboarding',
  path: '/agency/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryIdRoute = AppLibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedLibraryIndexRoute = AppSharedLibraryIndexRouteImport.update({
  id: '/shared-library/',
  path: '/shared-library/',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedLibraryIdRoute = AppSharedLibraryIdRouteImport.update({
  id: '/shared-library/$id',
  path: '/shared-library/$id',
  getParentRoute: () => AppRoute,
} as any)
const EmbedEmbedBrandAuditRoute = EmbedEmbedBrandAuditRouteImport.update({
  id: '/embed/brand-audit',
  path: '/embed/brand-audit',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedBrandStudioRoute = EmbedEmbedBrandStudioRouteImport.update({
  id: '/embed/brand-studio',
  path: '/embed/brand-studio',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedBrandVoiceRoute = EmbedEmbedBrandVoiceRouteImport.update({
  id: '/embed/brand-voice',
  path: '/embed/brand-voice',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedBuildRoute = EmbedEmbedBuildRouteImport.update({
  id: '/embed/build',
  path: '/embed/build',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedCampaignBriefRoute = EmbedEmbedCampaignBriefRouteImport.update({
  id: '/embed/campaign-brief',
  path: '/embed/campaign-brief',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedCompetitiveAnalyzerRoute =
  EmbedEmbedCompetitiveAnalyzerRouteImport.update({
    id: '/embed/competitive-analyzer',
    path: '/embed/competitive-analyzer',
    getParentRoute: () => EmbedRoute,
  } as any)
const EmbedEmbedEvaluateRoute = EmbedEmbedEvaluateRouteImport.update({
  id: '/embed/evaluate',
  path: '/embed/evaluate',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedImageGeneratorRoute =
  EmbedEmbedImageGeneratorRouteImport.update({
    id: '/embed/image-generator',
    path: '/embed/image-generator',
    getParentRoute: () => EmbedRoute,
  } as any)
const EmbedEmbedPlaygroundRoute = EmbedEmbedPlaygroundRouteImport.update({
  id: '/embed/playground',
  path: '/embed/playground',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedRegionAdapterRoute = EmbedEmbedRegionAdapterRouteImport.update({
  id: '/embed/region-adapter',
  path: '/embed/region-adapter',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedRegionalPlaybookRoute =
  EmbedEmbedRegionalPlaybookRouteImport.update({
    id: '/embed/regional-playbook',
    path: '/embed/regional-playbook',
    getParentRoute: () => EmbedRoute,
  } as any)
const EmbedEmbedSubjectOptimizerRoute =
  EmbedEmbedSubjectOptimizerRouteImport.update({
    id: '/embed/subject-optimizer',
    path: '/embed/subject-optimizer',
    getParentRoute: () => EmbedRoute,
  } as any)
const EmbedEmbedTranslateRoute = EmbedEmbedTranslateRouteImport.update({
  id: '/embed/translate',
  path: '/embed/translate',
  getParentRoute: () => EmbedRoute,
} as any)
const EmbedEmbedWebAnalyzerRoute = EmbedEmbedWebAnalyzerRouteImport.update({
  id: '/embed/web-analyzer',
  path: '/embed/web-analyzer',
  getParentRoute: () => EmbedRoute,
} as any)
const NdaSignSlugRoute = NdaSignSlugRouteImport.update({
  id: '/nda/sign/$slug',
  path: '/nda/sign/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAdminConsoleRoute = AppAdminAdminConsoleRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminContentDnaRoute = AppAdminAdminContentDnaRouteImport.update({
  id: '/admin/content-dna',
  path: '/admin/content-dna',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAdminUsersRoute = AppAdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSuperadminAdminAiTechnologyRoute =
  AppSuperadminAdminAiTechnologyRouteImport.update({
    id: '/admin/ai-technology',
    path: '/admin/ai-technology',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminCompassUsersRoute =
  AppSuperadminAdminCompassUsersRouteImport.update({
    id: '/admin/compass-users',
    path: '/admin/compass-users',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminCrmRoute = AppSuperadminAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSuperadminAdminLockerRoute =
  AppSuperadminAdminLockerRouteImport.update({
    id: '/admin/locker',
    path: '/admin/locker',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminNdaLinksRoute =
  AppSuperadminAdminNdaLinksRouteImport.update({
    id: '/admin/nda-links',
    path: '/admin/nda-links',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminPanelRoute = AppSuperadminAdminPanelRouteImport.update({
  id: '/admin/panel',
  path: '/admin/panel',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSuperadminAdminProspectOutreachRoute =
  AppSuperadminAdminProspectOutreachRouteImport.update({
    id: '/admin/prospect-outreach',
    path: '/admin/prospect-outreach',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminQaRoute = AppSuperadminAdminQaRouteImport.update({
  id: '/admin/qa',
  path: '/admin/qa',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSuperadminAdminSecurityEventsRoute =
  AppSuperadminAdminSecurityEventsRouteImport.update({
    id: '/admin/security-events',
    path: '/admin/security-events',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminSeedRoute = AppSuperadminAdminSeedRouteImport.update({
  id: '/admin/seed',
  path: '/admin/seed',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppAdminPersonalAiIndexRoute = AppAdminPersonalAiIndexRouteImport.update({
  id: '/admin/personal-ai/',
  path: '/admin/personal-ai/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminAdminInstitutionIdRoute =
  AppSuperadminAdminInstitutionIdRouteImport.update({
    id: '/admin/institution/$id',
    path: '/admin/institution/$id',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminPersonalAiEditsRoute =
  AppSuperadminAdminPersonalAiEditsRouteImport.update({
    id: '/admin/personal-ai/edits',
    path: '/admin/personal-ai/edits',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAdminUserIdRoute =
  AppSuperadminAdminUserIdRouteImport.update({
    id: '/admin/user/$id',
    path: '/admin/user/$id',
    getParentRoute: () => AppSuperadminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/copywriter-popout': typeof CopywriterPopoutRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-enterprise': typeof ForEnterpriseRoute
  '/higher-education-marketing-strategies': typeof HigherEducationMarketingStrategiesRoute
  '/login': typeof LoginRoute
  '/og-preview': typeof OgPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/request-access': typeof RequestAccessRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/try-copywriter': typeof TryCopywriterRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/approvals': typeof AppApprovalsRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/brand-audit': typeof AppBrandAuditRoute
  '/brand-studio': typeof AppBrandStudioRoute
  '/brand-voice': typeof AppBrandVoiceRoute
  '/build': typeof AppBuildRoute
  '/byoc': typeof AppByocRoute
  '/calendar': typeof AppCalendarRoute
  '/call-script': typeof AppCallScriptRoute
  '/campaign-brief': typeof AppCampaignBriefRoute
  '/campaign-dashboard': typeof AppCampaignDashboardRoute
  '/competitive-analyzer': typeof AppCompetitiveAnalyzerRoute
  '/content-dna': typeof AppContentDnaRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-preview': typeof AppEmailPreviewRoute
  '/evaluate': typeof AppEvaluateRoute
  '/feedback': typeof AppFeedbackRoute
  '/giving-day-planner': typeof AppGivingDayPlannerRoute
  '/image-generator': typeof AppImageGeneratorRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organization-settings': typeof AppOrganizationSettingsRoute
  '/playground': typeof AppPlaygroundRoute
  '/profile': typeof AppProfileRoute
  '/region-adapter': typeof AppRegionAdapterRoute
  '/regional-playbook': typeof AppRegionalPlaybookRoute
  '/settings': typeof AppSettingsRoute
  '/social-posts': typeof AppSocialPostsRoute
  '/stewardship-report': typeof AppStewardshipReportRoute
  '/strategy': typeof AppStrategyRoute
  '/subject-optimizer': typeof AppSubjectOptimizerRoute
  '/tools': typeof AppToolsRoute
  '/translate': typeof AppTranslateRoute
  '/university-settings': typeof AppUniversitySettingsRoute
  '/web-analyzer': typeof AppWebAnalyzerRoute
  '/agency/request-access': typeof AgencyRequestAccessRoute
  '/compass/locker': typeof CompassLockerRoute
  '/compass/setup': typeof CompassSetupRoute
  '/docs/salesforce-canvas': typeof DocsSalesforceCanvasRoute
  '/features/ai-copywriter': typeof FeaturesAiCopywriterRoute
  '/features/brand-audit': typeof FeaturesBrandAuditRoute
  '/features/brand-studio': typeof FeaturesBrandStudioRoute
  '/features/content-dna': typeof FeaturesContentDnaRoute
  '/features/evaluate': typeof FeaturesEvaluateRoute
  '/features/image-studio': typeof FeaturesImageStudioRoute
  '/features/journey-designer': typeof FeaturesJourneyDesignerRoute
  '/features/library': typeof FeaturesLibraryRoute
  '/features/message-builder': typeof FeaturesMessageBuilderRoute
  '/features/webcrawl': typeof FeaturesWebcrawlRoute
  '/integrations/salesforce-canvas': typeof IntegrationsSalesforceCanvasRoute
  '/compass/': typeof CompassIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/institution-dashboard': typeof AppAdminInstitutionDashboardRoute
  '/platform': typeof AppSuperadminPlatformRoute
  '/agency/analytics': typeof AppAgencyAnalyticsRoute
  '/agency/clients': typeof AppAgencyClientsRoute
  '/agency/dashboard': typeof AppAgencyDashboardRoute
  '/agency/onboarding': typeof AppAgencyOnboardingRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/shared-library/$id': typeof AppSharedLibraryIdRoute
  '/embed/brand-audit': typeof EmbedEmbedBrandAuditRoute
  '/embed/brand-studio': typeof EmbedEmbedBrandStudioRoute
  '/embed/brand-voice': typeof EmbedEmbedBrandVoiceRoute
  '/embed/build': typeof EmbedEmbedBuildRoute
  '/embed/campaign-brief': typeof EmbedEmbedCampaignBriefRoute
  '/embed/competitive-analyzer': typeof EmbedEmbedCompetitiveAnalyzerRoute
  '/embed/evaluate': typeof EmbedEmbedEvaluateRoute
  '/embed/image-generator': typeof EmbedEmbedImageGeneratorRoute
  '/embed/playground': typeof EmbedEmbedPlaygroundRoute
  '/embed/region-adapter': typeof EmbedEmbedRegionAdapterRoute
  '/embed/regional-playbook': typeof EmbedEmbedRegionalPlaybookRoute
  '/embed/subject-optimizer': typeof EmbedEmbedSubjectOptimizerRoute
  '/embed/translate': typeof EmbedEmbedTranslateRoute
  '/embed/web-analyzer': typeof EmbedEmbedWebAnalyzerRoute
  '/nda/sign/$slug': typeof NdaSignSlugRoute
  '/admin/': typeof AppAdminIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/shared-library/': typeof AppSharedLibraryIndexRoute
  '/admin/console': typeof AppAdminAdminConsoleRoute
  '/admin/content-dna': typeof AppAdminAdminContentDnaRoute
  '/admin/users': typeof AppAdminAdminUsersRoute
  '/admin/ai-technology': typeof AppSuperadminAdminAiTechnologyRoute
  '/admin/compass-users': typeof AppSuperadminAdminCompassUsersRoute
  '/admin/crm': typeof AppSuperadminAdminCrmRoute
  '/admin/locker': typeof AppSuperadminAdminLockerRoute
  '/admin/nda-links': typeof AppSuperadminAdminNdaLinksRoute
  '/admin/panel': typeof AppSuperadminAdminPanelRoute
  '/admin/prospect-outreach': typeof AppSuperadminAdminProspectOutreachRoute
  '/admin/qa': typeof AppSuperadminAdminQaRoute
  '/admin/security-events': typeof AppSuperadminAdminSecurityEventsRoute
  '/admin/seed': typeof AppSuperadminAdminSeedRoute
  '/admin/personal-ai/': typeof AppAdminPersonalAiIndexRoute
  '/admin/institution/$id': typeof AppSuperadminAdminInstitutionIdRoute
  '/admin/personal-ai/edits': typeof AppSuperadminAdminPersonalAiEditsRoute
  '/admin/user/$id': typeof AppSuperadminAdminUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/copywriter-popout': typeof CopywriterPopoutRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-enterprise': typeof ForEnterpriseRoute
  '/higher-education-marketing-strategies': typeof HigherEducationMarketingStrategiesRoute
  '/login': typeof LoginRoute
  '/og-preview': typeof OgPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/request-access': typeof RequestAccessRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/try-copywriter': typeof TryCopywriterRoute
  '/accessibility': typeof AppAccessibilityRoute
  '/approvals': typeof AppApprovalsRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/brand-audit': typeof AppBrandAuditRoute
  '/brand-studio': typeof AppBrandStudioRoute
  '/brand-voice': typeof AppBrandVoiceRoute
  '/build': typeof AppBuildRoute
  '/byoc': typeof AppByocRoute
  '/calendar': typeof AppCalendarRoute
  '/call-script': typeof AppCallScriptRoute
  '/campaign-brief': typeof AppCampaignBriefRoute
  '/campaign-dashboard': typeof AppCampaignDashboardRoute
  '/competitive-analyzer': typeof AppCompetitiveAnalyzerRoute
  '/content-dna': typeof AppContentDnaRoute
  '/dashboard': typeof AppDashboardRoute
  '/email-preview': typeof AppEmailPreviewRoute
  '/evaluate': typeof AppEvaluateRoute
  '/feedback': typeof AppFeedbackRoute
  '/giving-day-planner': typeof AppGivingDayPlannerRoute
  '/image-generator': typeof AppImageGeneratorRoute
  '/onboarding': typeof AppOnboardingRoute
  '/organization-settings': typeof AppOrganizationSettingsRoute
  '/playground': typeof AppPlaygroundRoute
  '/profile': typeof AppProfileRoute
  '/region-adapter': typeof AppRegionAdapterRoute
  '/regional-playbook': typeof AppRegionalPlaybookRoute
  '/settings': typeof AppSettingsRoute
  '/social-posts': typeof AppSocialPostsRoute
  '/stewardship-report': typeof AppStewardshipReportRoute
  '/strategy': typeof AppStrategyRoute
  '/subject-optimizer': typeof AppSubjectOptimizerRoute
  '/tools': typeof AppToolsRoute
  '/translate': typeof AppTranslateRoute
  '/university-settings': typeof AppUniversitySettingsRoute
  '/web-analyzer': typeof AppWebAnalyzerRoute
  '/agency/request-access': typeof AgencyRequestAccessRoute
  '/compass/locker': typeof CompassLockerRoute
  '/compass/setup': typeof CompassSetupRoute
  '/docs/salesforce-canvas': typeof DocsSalesforceCanvasRoute
  '/features/ai-copywriter': typeof FeaturesAiCopywriterRoute
  '/features/brand-audit': typeof FeaturesBrandAuditRoute
  '/features/brand-studio': typeof FeaturesBrandStudioRoute
  '/features/content-dna': typeof FeaturesContentDnaRoute
  '/features/evaluate': typeof FeaturesEvaluateRoute
  '/features/image-studio': typeof FeaturesImageStudioRoute
  '/features/journey-designer': typeof FeaturesJourneyDesignerRoute
  '/features/library': typeof FeaturesLibraryRoute
  '/features/message-builder': typeof FeaturesMessageBuilderRoute
  '/features/webcrawl': typeof FeaturesWebcrawlRoute
  '/integrations/salesforce-canvas': typeof IntegrationsSalesforceCanvasRoute
  '/compass': typeof CompassIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/institution-dashboard': typeof AppAdminInstitutionDashboardRoute
  '/platform': typeof AppSuperadminPlatformRoute
  '/agency/analytics': typeof AppAgencyAnalyticsRoute
  '/agency/clients': typeof AppAgencyClientsRoute
  '/agency/dashboard': typeof AppAgencyDashboardRoute
  '/agency/onboarding': typeof AppAgencyOnboardingRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/library/$id': typeof AppLibraryIdRoute
  '/shared-library/$id': typeof AppSharedLibraryIdRoute
  '/embed/brand-audit': typeof EmbedEmbedBrandAuditRoute
  '/embed/brand-studio': typeof EmbedEmbedBrandStudioRoute
  '/embed/brand-voice': typeof EmbedEmbedBrandVoiceRoute
  '/embed/build': typeof EmbedEmbedBuildRoute
  '/embed/campaign-brief': typeof EmbedEmbedCampaignBriefRoute
  '/embed/competitive-analyzer': typeof EmbedEmbedCompetitiveAnalyzerRoute
  '/embed/evaluate': typeof EmbedEmbedEvaluateRoute
  '/embed/image-generator': typeof EmbedEmbedImageGeneratorRoute
  '/embed/playground': typeof EmbedEmbedPlaygroundRoute
  '/embed/region-adapter': typeof EmbedEmbedRegionAdapterRoute
  '/embed/regional-playbook': typeof EmbedEmbedRegionalPlaybookRoute
  '/embed/subject-optimizer': typeof EmbedEmbedSubjectOptimizerRoute
  '/embed/translate': typeof EmbedEmbedTranslateRoute
  '/embed/web-analyzer': typeof EmbedEmbedWebAnalyzerRoute
  '/nda/sign/$slug': typeof NdaSignSlugRoute
  '/admin': typeof AppAdminIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/shared-library': typeof AppSharedLibraryIndexRoute
  '/admin/console': typeof AppAdminAdminConsoleRoute
  '/admin/content-dna': typeof AppAdminAdminContentDnaRoute
  '/admin/users': typeof AppAdminAdminUsersRoute
  '/admin/ai-technology': typeof AppSuperadminAdminAiTechnologyRoute
  '/admin/compass-users': typeof AppSuperadminAdminCompassUsersRoute
  '/admin/crm': typeof AppSuperadminAdminCrmRoute
  '/admin/locker': typeof AppSuperadminAdminLockerRoute
  '/admin/nda-links': typeof AppSuperadminAdminNdaLinksRoute
  '/admin/panel': typeof AppSuperadminAdminPanelRoute
  '/admin/prospect-outreach': typeof AppSuperadminAdminProspectOutreachRoute
  '/admin/qa': typeof AppSuperadminAdminQaRoute
  '/admin/security-events': typeof AppSuperadminAdminSecurityEventsRoute
  '/admin/seed': typeof AppSuperadminAdminSeedRoute
  '/admin/personal-ai': typeof AppAdminPersonalAiIndexRoute
  '/admin/institution/$id': typeof AppSuperadminAdminInstitutionIdRoute
  '/admin/personal-ai/edits': typeof AppSuperadminAdminPersonalAiEditsRoute
  '/admin/user/$id': typeof AppSuperadminAdminUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_embed': typeof EmbedRouteWithChildren
  '/about': typeof AboutRoute
  '/change-password': typeof ChangePasswordRoute
  '/copywriter-popout': typeof CopywriterPopoutRoute
  '/enterprise': typeof EnterpriseRoute
  '/for-agencies': typeof ForAgenciesRoute
  '/for-enterprise': typeof ForEnterpriseRoute
  '/higher-education-marketing-strategies': typeof HigherEducationMarketingStrategiesRoute
  '/login': typeof LoginRoute
  '/og-preview': typeof OgPreviewRoute
  '/privacy': typeof PrivacyRoute
  '/request-access': typeof RequestAccessRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/try-copywriter': typeof TryCopywriterRoute
  '/_app/_admin': typeof AppAdminRouteWithChildren
  '/_app/_superadmin': typeof AppSuperadminRouteWithChildren
  '/_app/accessibility': typeof AppAccessibilityRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/benchmarks': typeof AppBenchmarksRoute
  '/_app/brand-audit': typeof AppBrandAuditRoute
  '/_app/brand-studio': typeof AppBrandStudioRoute
  '/_app/brand-voice': typeof AppBrandVoiceRoute
  '/_app/build': typeof AppBuildRoute
  '/_app/byoc': typeof AppByocRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/call-script': typeof AppCallScriptRoute
  '/_app/campaign-brief': typeof AppCampaignBriefRoute
  '/_app/campaign-dashboard': typeof AppCampaignDashboardRoute
  '/_app/competitive-analyzer': typeof AppCompetitiveAnalyzerRoute
  '/_app/content-dna': typeof AppContentDnaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/email-preview': typeof AppEmailPreviewRoute
  '/_app/evaluate': typeof AppEvaluateRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/giving-day-planner': typeof AppGivingDayPlannerRoute
  '/_app/image-generator': typeof AppImageGeneratorRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/organization-settings': typeof AppOrganizationSettingsRoute
  '/_app/playground': typeof AppPlaygroundRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/region-adapter': typeof AppRegionAdapterRoute
  '/_app/regional-playbook': typeof AppRegionalPlaybookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social-posts': typeof AppSocialPostsRoute
  '/_app/stewardship-report': typeof AppStewardshipReportRoute
  '/_app/strategy': typeof AppStrategyRoute
  '/_app/subject-optimizer': typeof AppSubjectOptimizerRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/translate': typeof AppTranslateRoute
  '/_app/university-settings': typeof AppUniversitySettingsRoute
  '/_app/web-analyzer': typeof AppWebAnalyzerRoute
  '/agency/request-access': typeof AgencyRequestAccessRoute
  '/compass/locker': typeof CompassLockerRoute
  '/compass/setup': typeof CompassSetupRoute
  '/docs/salesforce-canvas': typeof DocsSalesforceCanvasRoute
  '/features/ai-copywriter': typeof FeaturesAiCopywriterRoute
  '/features/brand-audit': typeof FeaturesBrandAuditRoute
  '/features/brand-studio': typeof FeaturesBrandStudioRoute
  '/features/content-dna': typeof FeaturesContentDnaRoute
  '/features/evaluate': typeof FeaturesEvaluateRoute
  '/features/image-studio': typeof FeaturesImageStudioRoute
  '/features/journey-designer': typeof FeaturesJourneyDesignerRoute
  '/features/library': typeof FeaturesLibraryRoute
  '/features/message-builder': typeof FeaturesMessageBuilderRoute
  '/features/webcrawl': typeof FeaturesWebcrawlRoute
  '/integrations/salesforce-canvas': typeof IntegrationsSalesforceCanvasRoute
  '/compass/': typeof CompassIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_app/_admin/institution-dashboard': typeof AppAdminInstitutionDashboardRoute
  '/_app/_superadmin/platform': typeof AppSuperadminPlatformRoute
  '/_app/agency/analytics': typeof AppAgencyAnalyticsRoute
  '/_app/agency/clients': typeof AppAgencyClientsRoute
  '/_app/agency/dashboard': typeof AppAgencyDashboardRoute
  '/_app/agency/onboarding': typeof AppAgencyOnboardingRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/library/$id': typeof AppLibraryIdRoute
  '/_app/shared-library/$id': typeof AppSharedLibraryIdRoute
  '/_embed/embed/brand-audit': typeof EmbedEmbedBrandAuditRoute
  '/_embed/embed/brand-studio': typeof EmbedEmbedBrandStudioRoute
  '/_embed/embed/brand-voice': typeof EmbedEmbedBrandVoiceRoute
  '/_embed/embed/build': typeof EmbedEmbedBuildRoute
  '/_embed/embed/campaign-brief': typeof EmbedEmbedCampaignBriefRoute
  '/_embed/embed/competitive-analyzer': typeof EmbedEmbedCompetitiveAnalyzerRoute
  '/_embed/embed/evaluate': typeof EmbedEmbedEvaluateRoute
  '/_embed/embed/image-generator': typeof EmbedEmbedImageGeneratorRoute
  '/_embed/embed/playground': typeof EmbedEmbedPlaygroundRoute
  '/_embed/embed/region-adapter': typeof EmbedEmbedRegionAdapterRoute
  '/_embed/embed/regional-playbook': typeof EmbedEmbedRegionalPlaybookRoute
  '/_embed/embed/subject-optimizer': typeof EmbedEmbedSubjectOptimizerRoute
  '/_embed/embed/translate': typeof EmbedEmbedTranslateRoute
  '/_embed/embed/web-analyzer': typeof EmbedEmbedWebAnalyzerRoute
  '/nda/sign/$slug': typeof NdaSignSlugRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/shared-library/': typeof AppSharedLibraryIndexRoute
  '/_app/_admin/admin/console': typeof AppAdminAdminConsoleRoute
  '/_app/_admin/admin/content-dna': typeof AppAdminAdminContentDnaRoute
  '/_app/_admin/admin/users': typeof AppAdminAdminUsersRoute
  '/_app/_superadmin/admin/ai-technology': typeof AppSuperadminAdminAiTechnologyRoute
  '/_app/_superadmin/admin/compass-users': typeof AppSuperadminAdminCompassUsersRoute
  '/_app/_superadmin/admin/crm': typeof AppSuperadminAdminCrmRoute
  '/_app/_superadmin/admin/locker': typeof AppSuperadminAdminLockerRoute
  '/_app/_superadmin/admin/nda-links': typeof AppSuperadminAdminNdaLinksRoute
  '/_app/_superadmin/admin/panel': typeof AppSuperadminAdminPanelRoute
  '/_app/_superadmin/admin/prospect-outreach': typeof AppSuperadminAdminProspectOutreachRoute
  '/_app/_superadmin/admin/qa': typeof AppSuperadminAdminQaRoute
  '/_app/_superadmin/admin/security-events': typeof AppSuperadminAdminSecurityEventsRoute
  '/_app/_superadmin/admin/seed': typeof AppSuperadminAdminSeedRoute
  '/_app/admin/personal-ai/': typeof AppAdminPersonalAiIndexRoute
  '/_app/_superadmin/admin/institution/$id': typeof AppSuperadminAdminInstitutionIdRoute
  '/_app/_superadmin/admin/personal-ai/edits': typeof AppSuperadminAdminPersonalAiEditsRoute
  '/_app/_superadmin/admin/user/$id': typeof AppSuperadminAdminUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/change-password'
    | '/copywriter-popout'
    | '/enterprise'
    | '/for-agencies'
    | '/for-enterprise'
    | '/higher-education-marketing-strategies'
    | '/login'
    | '/og-preview'
    | '/privacy'
    | '/request-access'
    | '/setup'
    | '/terms'
    | '/try-copywriter'
    | '/accessibility'
    | '/approvals'
    | '/benchmarks'
    | '/brand-audit'
    | '/brand-studio'
    | '/brand-voice'
    | '/build'
    | '/byoc'
    | '/calendar'
    | '/call-script'
    | '/campaign-brief'
    | '/campaign-dashboard'
    | '/competitive-analyzer'
    | '/content-dna'
    | '/dashboard'
    | '/email-preview'
    | '/evaluate'
    | '/feedback'
    | '/giving-day-planner'
    | '/image-generator'
    | '/onboarding'
    | '/organization-settings'
    | '/playground'
    | '/profile'
    | '/region-adapter'
    | '/regional-playbook'
    | '/settings'
    | '/social-posts'
    | '/stewardship-report'
    | '/strategy'
    | '/subject-optimizer'
    | '/tools'
    | '/translate'
    | '/university-settings'
    | '/web-analyzer'
    | '/agency/request-access'
    | '/compass/locker'
    | '/compass/setup'
    | '/docs/salesforce-canvas'
    | '/features/ai-copywriter'
    | '/features/brand-audit'
    | '/features/brand-studio'
    | '/features/content-dna'
    | '/features/evaluate'
    | '/features/image-studio'
    | '/features/journey-designer'
    | '/features/library'
    | '/features/message-builder'
    | '/features/webcrawl'
    | '/integrations/salesforce-canvas'
    | '/compass/'
    | '/features/'
    | '/.lovable/oauth/consent'
    | '/institution-dashboard'
    | '/platform'
    | '/agency/analytics'
    | '/agency/clients'
    | '/agency/dashboard'
    | '/agency/onboarding'
    | '/collections/$id'
    | '/library/$id'
    | '/shared-library/$id'
    | '/embed/brand-audit'
    | '/embed/brand-studio'
    | '/embed/brand-voice'
    | '/embed/build'
    | '/embed/campaign-brief'
    | '/embed/competitive-analyzer'
    | '/embed/evaluate'
    | '/embed/image-generator'
    | '/embed/playground'
    | '/embed/region-adapter'
    | '/embed/regional-playbook'
    | '/embed/subject-optimizer'
    | '/embed/translate'
    | '/embed/web-analyzer'
    | '/nda/sign/$slug'
    | '/admin/'
    | '/library/'
    | '/shared-library/'
    | '/admin/console'
    | '/admin/content-dna'
    | '/admin/users'
    | '/admin/ai-technology'
    | '/admin/compass-users'
    | '/admin/crm'
    | '/admin/locker'
    | '/admin/nda-links'
    | '/admin/panel'
    | '/admin/prospect-outreach'
    | '/admin/qa'
    | '/admin/security-events'
    | '/admin/seed'
    | '/admin/personal-ai/'
    | '/admin/institution/$id'
    | '/admin/personal-ai/edits'
    | '/admin/user/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/change-password'
    | '/copywriter-popout'
    | '/enterprise'
    | '/for-agencies'
    | '/for-enterprise'
    | '/higher-education-marketing-strategies'
    | '/login'
    | '/og-preview'
    | '/privacy'
    | '/request-access'
    | '/setup'
    | '/terms'
    | '/try-copywriter'
    | '/accessibility'
    | '/approvals'
    | '/benchmarks'
    | '/brand-audit'
    | '/brand-studio'
    | '/brand-voice'
    | '/build'
    | '/byoc'
    | '/calendar'
    | '/call-script'
    | '/campaign-brief'
    | '/campaign-dashboard'
    | '/competitive-analyzer'
    | '/content-dna'
    | '/dashboard'
    | '/email-preview'
    | '/evaluate'
    | '/feedback'
    | '/giving-day-planner'
    | '/image-generator'
    | '/onboarding'
    | '/organization-settings'
    | '/playground'
    | '/profile'
    | '/region-adapter'
    | '/regional-playbook'
    | '/settings'
    | '/social-posts'
    | '/stewardship-report'
    | '/strategy'
    | '/subject-optimizer'
    | '/tools'
    | '/translate'
    | '/university-settings'
    | '/web-analyzer'
    | '/agency/request-access'
    | '/compass/locker'
    | '/compass/setup'
    | '/docs/salesforce-canvas'
    | '/features/ai-copywriter'
    | '/features/brand-audit'
    | '/features/brand-studio'
    | '/features/content-dna'
    | '/features/evaluate'
    | '/features/image-studio'
    | '/features/journey-designer'
    | '/features/library'
    | '/features/message-builder'
    | '/features/webcrawl'
    | '/integrations/salesforce-canvas'
    | '/compass'
    | '/features'
    | '/.lovable/oauth/consent'
    | '/institution-dashboard'
    | '/platform'
    | '/agency/analytics'
    | '/agency/clients'
    | '/agency/dashboard'
    | '/agency/onboarding'
    | '/collections/$id'
    | '/library/$id'
    | '/shared-library/$id'
    | '/embed/brand-audit'
    | '/embed/brand-studio'
    | '/embed/brand-voice'
    | '/embed/build'
    | '/embed/campaign-brief'
    | '/embed/competitive-analyzer'
    | '/embed/evaluate'
    | '/embed/image-generator'
    | '/embed/playground'
    | '/embed/region-adapter'
    | '/embed/regional-playbook'
    | '/embed/subject-optimizer'
    | '/embed/translate'
    | '/embed/web-analyzer'
    | '/nda/sign/$slug'
    | '/admin'
    | '/library'
    | '/shared-library'
    | '/admin/console'
    | '/admin/content-dna'
    | '/admin/users'
    | '/admin/ai-technology'
    | '/admin/compass-users'
    | '/admin/crm'
    | '/admin/locker'
    | '/admin/nda-links'
    | '/admin/panel'
    | '/admin/prospect-outreach'
    | '/admin/qa'
    | '/admin/security-events'
    | '/admin/seed'
    | '/admin/personal-ai'
    | '/admin/institution/$id'
    | '/admin/personal-ai/edits'
    | '/admin/user/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_embed'
    | '/about'
    | '/change-password'
    | '/copywriter-popout'
    | '/enterprise'
    | '/for-agencies'
    | '/for-enterprise'
    | '/higher-education-marketing-strategies'
    | '/login'
    | '/og-preview'
    | '/privacy'
    | '/request-access'
    | '/setup'
    | '/terms'
    | '/try-copywriter'
    | '/_app/_admin'
    | '/_app/_superadmin'
    | '/_app/accessibility'
    | '/_app/approvals'
    | '/_app/benchmarks'
    | '/_app/brand-audit'
    | '/_app/brand-studio'
    | '/_app/brand-voice'
    | '/_app/build'
    | '/_app/byoc'
    | '/_app/calendar'
    | '/_app/call-script'
    | '/_app/campaign-brief'
    | '/_app/campaign-dashboard'
    | '/_app/competitive-analyzer'
    | '/_app/content-dna'
    | '/_app/dashboard'
    | '/_app/email-preview'
    | '/_app/evaluate'
    | '/_app/feedback'
    | '/_app/giving-day-planner'
    | '/_app/image-generator'
    | '/_app/onboarding'
    | '/_app/organization-settings'
    | '/_app/playground'
    | '/_app/profile'
    | '/_app/region-adapter'
    | '/_app/regional-playbook'
    | '/_app/settings'
    | '/_app/social-posts'
    | '/_app/stewardship-report'
    | '/_app/strategy'
    | '/_app/subject-optimizer'
    | '/_app/tools'
    | '/_app/translate'
    | '/_app/university-settings'
    | '/_app/web-analyzer'
    | '/agency/request-access'
    | '/compass/locker'
    | '/compass/setup'
    | '/docs/salesforce-canvas'
    | '/features/ai-copywriter'
    | '/features/brand-audit'
    | '/features/brand-studio'
    | '/features/content-dna'
    | '/features/evaluate'
    | '/features/image-studio'
    | '/features/journey-designer'
    | '/features/library'
    | '/features/message-builder'
    | '/features/webcrawl'
    | '/integrations/salesforce-canvas'
    | '/compass/'
    | '/features/'
    | '/.lovable/oauth/consent'
    | '/_app/_admin/institution-dashboard'
    | '/_app/_superadmin/platform'
    | '/_app/agency/analytics'
    | '/_app/agency/clients'
    | '/_app/agency/dashboard'
    | '/_app/agency/onboarding'
    | '/_app/collections/$id'
    | '/_app/library/$id'
    | '/_app/shared-library/$id'
    | '/_embed/embed/brand-audit'
    | '/_embed/embed/brand-studio'
    | '/_embed/embed/brand-voice'
    | '/_embed/embed/build'
    | '/_embed/embed/campaign-brief'
    | '/_embed/embed/competitive-analyzer'
    | '/_embed/embed/evaluate'
    | '/_embed/embed/image-generator'
    | '/_embed/embed/playground'
    | '/_embed/embed/region-adapter'
    | '/_embed/embed/regional-playbook'
    | '/_embed/embed/subject-optimizer'
    | '/_embed/embed/translate'
    | '/_embed/embed/web-analyzer'
    | '/nda/sign/$slug'
    | '/_app/admin/'
    | '/_app/library/'
    | '/_app/shared-library/'
    | '/_app/_admin/admin/console'
    | '/_app/_admin/admin/content-dna'
    | '/_app/_admin/admin/users'
    | '/_app/_superadmin/admin/ai-technology'
    | '/_app/_superadmin/admin/compass-users'
    | '/_app/_superadmin/admin/crm'
    | '/_app/_superadmin/admin/locker'
    | '/_app/_superadmin/admin/nda-links'
    | '/_app/_superadmin/admin/panel'
    | '/_app/_superadmin/admin/prospect-outreach'
    | '/_app/_superadmin/admin/qa'
    | '/_app/_superadmin/admin/security-events'
    | '/_app/_superadmin/admin/seed'
    | '/_app/admin/personal-ai/'
    | '/_app/_superadmin/admin/institution/$id'
    | '/_app/_superadmin/admin/personal-ai/edits'
    | '/_app/_superadmin/admin/user/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EmbedRoute: typeof EmbedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  CopywriterPopoutRoute: typeof CopywriterPopoutRoute
  EnterpriseRoute: typeof EnterpriseRoute
  ForAgenciesRoute: typeof ForAgenciesRoute
  ForEnterpriseRoute: typeof ForEnterpriseRoute
  HigherEducationMarketingStrategiesRoute: typeof HigherEducationMarketingStrategiesRoute
  LoginRoute: typeof LoginRoute
  OgPreviewRoute: typeof OgPreviewRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestAccessRoute: typeof RequestAccessRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  TryCopywriterRoute: typeof TryCopywriterRoute
  AgencyRequestAccessRoute: typeof AgencyRequestAccessRoute
  CompassLockerRoute: typeof CompassLockerRoute
  CompassSetupRoute: typeof CompassSetupRoute
  DocsSalesforceCanvasRoute: typeof DocsSalesforceCanvasRoute
  FeaturesAiCopywriterRoute: typeof FeaturesAiCopywriterRoute
  FeaturesBrandAuditRoute: typeof FeaturesBrandAuditRoute
  FeaturesBrandStudioRoute: typeof FeaturesBrandStudioRoute
  FeaturesContentDnaRoute: typeof FeaturesContentDnaRoute
  FeaturesEvaluateRoute: typeof FeaturesEvaluateRoute
  FeaturesImageStudioRoute: typeof FeaturesImageStudioRoute
  FeaturesJourneyDesignerRoute: typeof FeaturesJourneyDesignerRoute
  FeaturesLibraryRoute: typeof FeaturesLibraryRoute
  FeaturesMessageBuilderRoute: typeof FeaturesMessageBuilderRoute
  FeaturesWebcrawlRoute: typeof FeaturesWebcrawlRoute
  IntegrationsSalesforceCanvasRoute: typeof IntegrationsSalesforceCanvasRoute
  CompassIndexRoute: typeof CompassIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  NdaSignSlugRoute: typeof NdaSignSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_embed': {
      id: '/_embed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copywriter-popout': {
      id: '/copywriter-popout'
      path: '/copywriter-popout'
      fullPath: '/copywriter-popout'
      preLoaderRoute: typeof CopywriterPopoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-agencies': {
      id: '/for-agencies'
      path: '/for-agencies'
      fullPath: '/for-agencies'
      preLoaderRoute: typeof ForAgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-enterprise': {
      id: '/for-enterprise'
      path: '/for-enterprise'
      fullPath: '/for-enterprise'
      preLoaderRoute: typeof ForEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/higher-education-marketing-strategies': {
      id: '/higher-education-marketing-strategies'
      path: '/higher-education-marketing-strategies'
      fullPath: '/higher-education-marketing-strategies'
      preLoaderRoute: typeof HigherEducationMarketingStrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-preview': {
      id: '/og-preview'
      path: '/og-preview'
      fullPath: '/og-preview'
      preLoaderRoute: typeof OgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try-copywriter': {
      id: '/try-copywriter'
      path: '/try-copywriter'
      fullPath: '/try-copywriter'
      preLoaderRoute: typeof TryCopywriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin': {
      id: '/_app/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_superadmin': {
      id: '/_app/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppSuperadminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accessibility': {
      id: '/_app/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AppAccessibilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/benchmarks': {
      id: '/_app/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof AppBenchmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand-audit': {
      id: '/_app/brand-audit'
      path: '/brand-audit'
      fullPath: '/brand-audit'
      preLoaderRoute: typeof AppBrandAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand-studio': {
      id: '/_app/brand-studio'
      path: '/brand-studio'
      fullPath: '/brand-studio'
      preLoaderRoute: typeof AppBrandStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand-voice': {
      id: '/_app/brand-voice'
      path: '/brand-voice'
      fullPath: '/brand-voice'
      preLoaderRoute: typeof AppBrandVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/build': {
      id: '/_app/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof AppBuildRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/byoc': {
      id: '/_app/byoc'
      path: '/byoc'
      fullPath: '/byoc'
      preLoaderRoute: typeof AppByocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-script': {
      id: '/_app/call-script'
      path: '/call-script'
      fullPath: '/call-script'
      preLoaderRoute: typeof AppCallScriptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaign-brief': {
      id: '/_app/campaign-brief'
      path: '/campaign-brief'
      fullPath: '/campaign-brief'
      preLoaderRoute: typeof AppCampaignBriefRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaign-dashboard': {
      id: '/_app/campaign-dashboard'
      path: '/campaign-dashboard'
      fullPath: '/campaign-dashboard'
      preLoaderRoute: typeof AppCampaignDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitive-analyzer': {
      id: '/_app/competitive-analyzer'
      path: '/competitive-analyzer'
      fullPath: '/competitive-analyzer'
      preLoaderRoute: typeof AppCompetitiveAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content-dna': {
      id: '/_app/content-dna'
      path: '/content-dna'
      fullPath: '/content-dna'
      preLoaderRoute: typeof AppContentDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-preview': {
      id: '/_app/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof AppEmailPreviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evaluate': {
      id: '/_app/evaluate'
      path: '/evaluate'
      fullPath: '/evaluate'
      preLoaderRoute: typeof AppEvaluateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/giving-day-planner': {
      id: '/_app/giving-day-planner'
      path: '/giving-day-planner'
      fullPath: '/giving-day-planner'
      preLoaderRoute: typeof AppGivingDayPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/image-generator': {
      id: '/_app/image-generator'
      path: '/image-generator'
      fullPath: '/image-generator'
      preLoaderRoute: typeof AppImageGeneratorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organization-settings': {
      id: '/_app/organization-settings'
      path: '/organization-settings'
      fullPath: '/organization-settings'
      preLoaderRoute: typeof AppOrganizationSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/region-adapter': {
      id: '/_app/region-adapter'
      path: '/region-adapter'
      fullPath: '/region-adapter'
      preLoaderRoute: typeof AppRegionAdapterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/regional-playbook': {
      id: '/_app/regional-playbook'
      path: '/regional-playbook'
      fullPath: '/regional-playbook'
      preLoaderRoute: typeof AppRegionalPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social-posts': {
      id: '/_app/social-posts'
      path: '/social-posts'
      fullPath: '/social-posts'
      preLoaderRoute: typeof AppSocialPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stewardship-report': {
      id: '/_app/stewardship-report'
      path: '/stewardship-report'
      fullPath: '/stewardship-report'
      preLoaderRoute: typeof AppStewardshipReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/strategy': {
      id: '/_app/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof AppStrategyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subject-optimizer': {
      id: '/_app/subject-optimizer'
      path: '/subject-optimizer'
      fullPath: '/subject-optimizer'
      preLoaderRoute: typeof AppSubjectOptimizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/translate': {
      id: '/_app/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof AppTranslateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/university-settings': {
      id: '/_app/university-settings'
      path: '/university-settings'
      fullPath: '/university-settings'
      preLoaderRoute: typeof AppUniversitySettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/web-analyzer': {
      id: '/_app/web-analyzer'
      path: '/web-analyzer'
      fullPath: '/web-analyzer'
      preLoaderRoute: typeof AppWebAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/agency/request-access': {
      id: '/agency/request-access'
      path: '/agency/request-access'
      fullPath: '/agency/request-access'
      preLoaderRoute: typeof AgencyRequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass/': {
      id: '/compass/'
      path: '/compass'
      fullPath: '/compass/'
      preLoaderRoute: typeof CompassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass/locker': {
      id: '/compass/locker'
      path: '/compass/locker'
      fullPath: '/compass/locker'
      preLoaderRoute: typeof CompassLockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compass/setup': {
      id: '/compass/setup'
      path: '/compass/setup'
      fullPath: '/compass/setup'
      preLoaderRoute: typeof CompassSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/salesforce-canvas': {
      id: '/docs/salesforce-canvas'
      path: '/docs/salesforce-canvas'
      fullPath: '/docs/salesforce-canvas'
      preLoaderRoute: typeof DocsSalesforceCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/ai-copywriter': {
      id: '/features/ai-copywriter'
      path: '/features/ai-copywriter'
      fullPath: '/features/ai-copywriter'
      preLoaderRoute: typeof FeaturesAiCopywriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/brand-audit': {
      id: '/features/brand-audit'
      path: '/features/brand-audit'
      fullPath: '/features/brand-audit'
      preLoaderRoute: typeof FeaturesBrandAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/brand-studio': {
      id: '/features/brand-studio'
      path: '/features/brand-studio'
      fullPath: '/features/brand-studio'
      preLoaderRoute: typeof FeaturesBrandStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/content-dna': {
      id: '/features/content-dna'
      path: '/features/content-dna'
      fullPath: '/features/content-dna'
      preLoaderRoute: typeof FeaturesContentDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/evaluate': {
      id: '/features/evaluate'
      path: '/features/evaluate'
      fullPath: '/features/evaluate'
      preLoaderRoute: typeof FeaturesEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/image-studio': {
      id: '/features/image-studio'
      path: '/features/image-studio'
      fullPath: '/features/image-studio'
      preLoaderRoute: typeof FeaturesImageStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/journey-designer': {
      id: '/features/journey-designer'
      path: '/features/journey-designer'
      fullPath: '/features/journey-designer'
      preLoaderRoute: typeof FeaturesJourneyDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/library': {
      id: '/features/library'
      path: '/features/library'
      fullPath: '/features/library'
      preLoaderRoute: typeof FeaturesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/message-builder': {
      id: '/features/message-builder'
      path: '/features/message-builder'
      fullPath: '/features/message-builder'
      preLoaderRoute: typeof FeaturesMessageBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/webcrawl': {
      id: '/features/webcrawl'
      path: '/features/webcrawl'
      fullPath: '/features/webcrawl'
      preLoaderRoute: typeof FeaturesWebcrawlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/salesforce-canvas': {
      id: '/integrations/salesforce-canvas'
      path: '/integrations/salesforce-canvas'
      fullPath: '/integrations/salesforce-canvas'
      preLoaderRoute: typeof IntegrationsSalesforceCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin/institution-dashboard': {
      id: '/_app/_admin/institution-dashboard'
      path: '/institution-dashboard'
      fullPath: '/institution-dashboard'
      preLoaderRoute: typeof AppAdminInstitutionDashboardRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_superadmin/platform': {
      id: '/_app/_superadmin/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AppSuperadminPlatformRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency/analytics': {
      id: '/_app/agency/analytics'
      path: '/agency/analytics'
      fullPath: '/agency/analytics'
      preLoaderRoute: typeof AppAgencyAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency/clients': {
      id: '/_app/agency/clients'
      path: '/agency/clients'
      fullPath: '/agency/clients'
      preLoaderRoute: typeof AppAgencyClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency/dashboard': {
      id: '/_app/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AppAgencyDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agency/onboarding': {
      id: '/_app/agency/onboarding'
      path: '/agency/onboarding'
      fullPath: '/agency/onboarding'
      preLoaderRoute: typeof AppAgencyOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library/$id': {
      id: '/_app/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AppLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared-library/': {
      id: '/_app/shared-library/'
      path: '/shared-library'
      fullPath: '/shared-library/'
      preLoaderRoute: typeof AppSharedLibraryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared-library/$id': {
      id: '/_app/shared-library/$id'
      path: '/shared-library/$id'
      fullPath: '/shared-library/$id'
      preLoaderRoute: typeof AppSharedLibraryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_embed/embed/brand-audit': {
      id: '/_embed/embed/brand-audit'
      path: '/embed/brand-audit'
      fullPath: '/embed/brand-audit'
      preLoaderRoute: typeof EmbedEmbedBrandAuditRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/brand-studio': {
      id: '/_embed/embed/brand-studio'
      path: '/embed/brand-studio'
      fullPath: '/embed/brand-studio'
      preLoaderRoute: typeof EmbedEmbedBrandStudioRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/brand-voice': {
      id: '/_embed/embed/brand-voice'
      path: '/embed/brand-voice'
      fullPath: '/embed/brand-voice'
      preLoaderRoute: typeof EmbedEmbedBrandVoiceRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/build': {
      id: '/_embed/embed/build'
      path: '/embed/build'
      fullPath: '/embed/build'
      preLoaderRoute: typeof EmbedEmbedBuildRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/campaign-brief': {
      id: '/_embed/embed/campaign-brief'
      path: '/embed/campaign-brief'
      fullPath: '/embed/campaign-brief'
      preLoaderRoute: typeof EmbedEmbedCampaignBriefRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/competitive-analyzer': {
      id: '/_embed/embed/competitive-analyzer'
      path: '/embed/competitive-analyzer'
      fullPath: '/embed/competitive-analyzer'
      preLoaderRoute: typeof EmbedEmbedCompetitiveAnalyzerRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/evaluate': {
      id: '/_embed/embed/evaluate'
      path: '/embed/evaluate'
      fullPath: '/embed/evaluate'
      preLoaderRoute: typeof EmbedEmbedEvaluateRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/image-generator': {
      id: '/_embed/embed/image-generator'
      path: '/embed/image-generator'
      fullPath: '/embed/image-generator'
      preLoaderRoute: typeof EmbedEmbedImageGeneratorRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/playground': {
      id: '/_embed/embed/playground'
      path: '/embed/playground'
      fullPath: '/embed/playground'
      preLoaderRoute: typeof EmbedEmbedPlaygroundRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/region-adapter': {
      id: '/_embed/embed/region-adapter'
      path: '/embed/region-adapter'
      fullPath: '/embed/region-adapter'
      preLoaderRoute: typeof EmbedEmbedRegionAdapterRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/regional-playbook': {
      id: '/_embed/embed/regional-playbook'
      path: '/embed/regional-playbook'
      fullPath: '/embed/regional-playbook'
      preLoaderRoute: typeof EmbedEmbedRegionalPlaybookRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/subject-optimizer': {
      id: '/_embed/embed/subject-optimizer'
      path: '/embed/subject-optimizer'
      fullPath: '/embed/subject-optimizer'
      preLoaderRoute: typeof EmbedEmbedSubjectOptimizerRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/translate': {
      id: '/_embed/embed/translate'
      path: '/embed/translate'
      fullPath: '/embed/translate'
      preLoaderRoute: typeof EmbedEmbedTranslateRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/_embed/embed/web-analyzer': {
      id: '/_embed/embed/web-analyzer'
      path: '/embed/web-analyzer'
      fullPath: '/embed/web-analyzer'
      preLoaderRoute: typeof EmbedEmbedWebAnalyzerRouteImport
      parentRoute: typeof EmbedRoute
    }
    '/nda/sign/$slug': {
      id: '/nda/sign/$slug'
      path: '/nda/sign/$slug'
      fullPath: '/nda/sign/$slug'
      preLoaderRoute: typeof NdaSignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_admin/admin/console': {
      id: '/_app/_admin/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AppAdminAdminConsoleRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/content-dna': {
      id: '/_app/_admin/admin/content-dna'
      path: '/admin/content-dna'
      fullPath: '/admin/content-dna'
      preLoaderRoute: typeof AppAdminAdminContentDnaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_admin/admin/users': {
      id: '/_app/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/_superadmin/admin/ai-technology': {
      id: '/_app/_superadmin/admin/ai-technology'
      path: '/admin/ai-technology'
      fullPath: '/admin/ai-technology'
      preLoaderRoute: typeof AppSuperadminAdminAiTechnologyRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/compass-users': {
      id: '/_app/_superadmin/admin/compass-users'
      path: '/admin/compass-users'
      fullPath: '/admin/compass-users'
      preLoaderRoute: typeof AppSuperadminAdminCompassUsersRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/crm': {
      id: '/_app/_superadmin/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AppSuperadminAdminCrmRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/locker': {
      id: '/_app/_superadmin/admin/locker'
      path: '/admin/locker'
      fullPath: '/admin/locker'
      preLoaderRoute: typeof AppSuperadminAdminLockerRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/nda-links': {
      id: '/_app/_superadmin/admin/nda-links'
      path: '/admin/nda-links'
      fullPath: '/admin/nda-links'
      preLoaderRoute: typeof AppSuperadminAdminNdaLinksRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/panel': {
      id: '/_app/_superadmin/admin/panel'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AppSuperadminAdminPanelRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/prospect-outreach': {
      id: '/_app/_superadmin/admin/prospect-outreach'
      path: '/admin/prospect-outreach'
      fullPath: '/admin/prospect-outreach'
      preLoaderRoute: typeof AppSuperadminAdminProspectOutreachRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/qa': {
      id: '/_app/_superadmin/admin/qa'
      path: '/admin/qa'
      fullPath: '/admin/qa'
      preLoaderRoute: typeof AppSuperadminAdminQaRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/security-events': {
      id: '/_app/_superadmin/admin/security-events'
      path: '/admin/security-events'
      fullPath: '/admin/security-events'
      preLoaderRoute: typeof AppSuperadminAdminSecurityEventsRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/seed': {
      id: '/_app/_superadmin/admin/seed'
      path: '/admin/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AppSuperadminAdminSeedRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/admin/personal-ai/': {
      id: '/_app/admin/personal-ai/'
      path: '/admin/personal-ai'
      fullPath: '/admin/personal-ai/'
      preLoaderRoute: typeof AppAdminPersonalAiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_superadmin/admin/institution/$id': {
      id: '/_app/_superadmin/admin/institution/$id'
      path: '/admin/institution/$id'
      fullPath: '/admin/institution/$id'
      preLoaderRoute: typeof AppSuperadminAdminInstitutionIdRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/personal-ai/edits': {
      id: '/_app/_superadmin/admin/personal-ai/edits'
      path: '/admin/personal-ai/edits'
      fullPath: '/admin/personal-ai/edits'
      preLoaderRoute: typeof AppSuperadminAdminPersonalAiEditsRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/_superadmin/admin/user/$id': {
      id: '/_app/_superadmin/admin/user/$id'
      path: '/admin/user/$id'
      fullPath: '/admin/user/$id'
      preLoaderRoute: typeof AppSuperadminAdminUserIdRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminInstitutionDashboardRoute: typeof AppAdminInstitutionDashboardRoute
  AppAdminAdminConsoleRoute: typeof AppAdminAdminConsoleRoute
  AppAdminAdminContentDnaRoute: typeof AppAdminAdminContentDnaRoute
  AppAdminAdminUsersRoute: typeof AppAdminAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminInstitutionDashboardRoute: AppAdminInstitutionDashboardRoute,
  AppAdminAdminConsoleRoute: AppAdminAdminConsoleRoute,
  AppAdminAdminContentDnaRoute: AppAdminAdminContentDnaRoute,
  AppAdminAdminUsersRoute: AppAdminAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppSuperadminRouteChildren {
  AppSuperadminPlatformRoute: typeof AppSuperadminPlatformRoute
  AppSuperadminAdminAiTechnologyRoute: typeof AppSuperadminAdminAiTechnologyRoute
  AppSuperadminAdminCompassUsersRoute: typeof AppSuperadminAdminCompassUsersRoute
  AppSuperadminAdminCrmRoute: typeof AppSuperadminAdminCrmRoute
  AppSuperadminAdminLockerRoute: typeof AppSuperadminAdminLockerRoute
  AppSuperadminAdminNdaLinksRoute: typeof AppSuperadminAdminNdaLinksRoute
  AppSuperadminAdminPanelRoute: typeof AppSuperadminAdminPanelRoute
  AppSuperadminAdminProspectOutreachRoute: typeof AppSuperadminAdminProspectOutreachRoute
  AppSuperadminAdminQaRoute: typeof AppSuperadminAdminQaRoute
  AppSuperadminAdminSecurityEventsRoute: typeof AppSuperadminAdminSecurityEventsRoute
  AppSuperadminAdminSeedRoute: typeof AppSuperadminAdminSeedRoute
  AppSuperadminAdminInstitutionIdRoute: typeof AppSuperadminAdminInstitutionIdRoute
  AppSuperadminAdminPersonalAiEditsRoute: typeof AppSuperadminAdminPersonalAiEditsRoute
  AppSuperadminAdminUserIdRoute: typeof AppSuperadminAdminUserIdRoute
}

const AppSuperadminRouteChildren: AppSuperadminRouteChildren = {
  AppSuperadminPlatformRoute: AppSuperadminPlatformRoute,
  AppSuperadminAdminAiTechnologyRoute: AppSuperadminAdminAiTechnologyRoute,
  AppSuperadminAdminCompassUsersRoute: AppSuperadminAdminCompassUsersRoute,
  AppSuperadminAdminCrmRoute: AppSuperadminAdminCrmRoute,
  AppSuperadminAdminLockerRoute: AppSuperadminAdminLockerRoute,
  AppSuperadminAdminNdaLinksRoute: AppSuperadminAdminNdaLinksRoute,
  AppSuperadminAdminPanelRoute: AppSuperadminAdminPanelRoute,
  AppSuperadminAdminProspectOutreachRoute:
    AppSuperadminAdminProspectOutreachRoute,
  AppSuperadminAdminQaRoute: AppSuperadminAdminQaRoute,
  AppSuperadminAdminSecurityEventsRoute: AppSuperadminAdminSecurityEventsRoute,
  AppSuperadminAdminSeedRoute: AppSuperadminAdminSeedRoute,
  AppSuperadminAdminInstitutionIdRoute: AppSuperadminAdminInstitutionIdRoute,
  AppSuperadminAdminPersonalAiEditsRoute:
    AppSuperadminAdminPersonalAiEditsRoute,
  AppSuperadminAdminUserIdRoute: AppSuperadminAdminUserIdRoute,
}

const AppSuperadminRouteWithChildren = AppSuperadminRoute._addFileChildren(
  AppSuperadminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppSuperadminRoute: typeof AppSuperadminRouteWithChildren
  AppAccessibilityRoute: typeof AppAccessibilityRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBenchmarksRoute: typeof AppBenchmarksRoute
  AppBrandAuditRoute: typeof AppBrandAuditRoute
  AppBrandStudioRoute: typeof AppBrandStudioRoute
  AppBrandVoiceRoute: typeof AppBrandVoiceRoute
  AppBuildRoute: typeof AppBuildRoute
  AppByocRoute: typeof AppByocRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCallScriptRoute: typeof AppCallScriptRoute
  AppCampaignBriefRoute: typeof AppCampaignBriefRoute
  AppCampaignDashboardRoute: typeof AppCampaignDashboardRoute
  AppCompetitiveAnalyzerRoute: typeof AppCompetitiveAnalyzerRoute
  AppContentDnaRoute: typeof AppContentDnaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmailPreviewRoute: typeof AppEmailPreviewRoute
  AppEvaluateRoute: typeof AppEvaluateRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppGivingDayPlannerRoute: typeof AppGivingDayPlannerRoute
  AppImageGeneratorRoute: typeof AppImageGeneratorRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrganizationSettingsRoute: typeof AppOrganizationSettingsRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegionAdapterRoute: typeof AppRegionAdapterRoute
  AppRegionalPlaybookRoute: typeof AppRegionalPlaybookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialPostsRoute: typeof AppSocialPostsRoute
  AppStewardshipReportRoute: typeof AppStewardshipReportRoute
  AppStrategyRoute: typeof AppStrategyRoute
  AppSubjectOptimizerRoute: typeof AppSubjectOptimizerRoute
  AppToolsRoute: typeof AppToolsRoute
  AppTranslateRoute: typeof AppTranslateRoute
  AppUniversitySettingsRoute: typeof AppUniversitySettingsRoute
  AppWebAnalyzerRoute: typeof AppWebAnalyzerRoute
  AppAgencyAnalyticsRoute: typeof AppAgencyAnalyticsRoute
  AppAgencyClientsRoute: typeof AppAgencyClientsRoute
  AppAgencyDashboardRoute: typeof AppAgencyDashboardRoute
  AppAgencyOnboardingRoute: typeof AppAgencyOnboardingRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppLibraryIdRoute: typeof AppLibraryIdRoute
  AppSharedLibraryIdRoute: typeof AppSharedLibraryIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppSharedLibraryIndexRoute: typeof AppSharedLibraryIndexRoute
  AppAdminPersonalAiIndexRoute: typeof AppAdminPersonalAiIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppSuperadminRoute: AppSuperadminRouteWithChildren,
  AppAccessibilityRoute: AppAccessibilityRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBenchmarksRoute: AppBenchmarksRoute,
  AppBrandAuditRoute: AppBrandAuditRoute,
  AppBrandStudioRoute: AppBrandStudioRoute,
  AppBrandVoiceRoute: AppBrandVoiceRoute,
  AppBuildRoute: AppBuildRoute,
  AppByocRoute: AppByocRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCallScriptRoute: AppCallScriptRoute,
  AppCampaignBriefRoute: AppCampaignBriefRoute,
  AppCampaignDashboardRoute: AppCampaignDashboardRoute,
  AppCompetitiveAnalyzerRoute: AppCompetitiveAnalyzerRoute,
  AppContentDnaRoute: AppContentDnaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmailPreviewRoute: AppEmailPreviewRoute,
  AppEvaluateRoute: AppEvaluateRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppGivingDayPlannerRoute: AppGivingDayPlannerRoute,
  AppImageGeneratorRoute: AppImageGeneratorRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrganizationSettingsRoute: AppOrganizationSettingsRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegionAdapterRoute: AppRegionAdapterRoute,
  AppRegionalPlaybookRoute: AppRegionalPlaybookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialPostsRoute: AppSocialPostsRoute,
  AppStewardshipReportRoute: AppStewardshipReportRoute,
  AppStrategyRoute: AppStrategyRoute,
  AppSubjectOptimizerRoute: AppSubjectOptimizerRoute,
  AppToolsRoute: AppToolsRoute,
  AppTranslateRoute: AppTranslateRoute,
  AppUniversitySettingsRoute: AppUniversitySettingsRoute,
  AppWebAnalyzerRoute: AppWebAnalyzerRoute,
  AppAgencyAnalyticsRoute: AppAgencyAnalyticsRoute,
  AppAgencyClientsRoute: AppAgencyClientsRoute,
  AppAgencyDashboardRoute: AppAgencyDashboardRoute,
  AppAgencyOnboardingRoute: AppAgencyOnboardingRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppLibraryIdRoute: AppLibraryIdRoute,
  AppSharedLibraryIdRoute: AppSharedLibraryIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppSharedLibraryIndexRoute: AppSharedLibraryIndexRoute,
  AppAdminPersonalAiIndexRoute: AppAdminPersonalAiIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface EmbedRouteChildren {
  EmbedEmbedBrandAuditRoute: typeof EmbedEmbedBrandAuditRoute
  EmbedEmbedBrandStudioRoute: typeof EmbedEmbedBrandStudioRoute
  EmbedEmbedBrandVoiceRoute: typeof EmbedEmbedBrandVoiceRoute
  EmbedEmbedBuildRoute: typeof EmbedEmbedBuildRoute
  EmbedEmbedCampaignBriefRoute: typeof EmbedEmbedCampaignBriefRoute
  EmbedEmbedCompetitiveAnalyzerRoute: typeof EmbedEmbedCompetitiveAnalyzerRoute
  EmbedEmbedEvaluateRoute: typeof EmbedEmbedEvaluateRoute
  EmbedEmbedImageGeneratorRoute: typeof EmbedEmbedImageGeneratorRoute
  EmbedEmbedPlaygroundRoute: typeof EmbedEmbedPlaygroundRoute
  EmbedEmbedRegionAdapterRoute: typeof EmbedEmbedRegionAdapterRoute
  EmbedEmbedRegionalPlaybookRoute: typeof EmbedEmbedRegionalPlaybookRoute
  EmbedEmbedSubjectOptimizerRoute: typeof EmbedEmbedSubjectOptimizerRoute
  EmbedEmbedTranslateRoute: typeof EmbedEmbedTranslateRoute
  EmbedEmbedWebAnalyzerRoute: typeof EmbedEmbedWebAnalyzerRoute
}

const EmbedRouteChildren: EmbedRouteChildren = {
  EmbedEmbedBrandAuditRoute: EmbedEmbedBrandAuditRoute,
  EmbedEmbedBrandStudioRoute: EmbedEmbedBrandStudioRoute,
  EmbedEmbedBrandVoiceRoute: EmbedEmbedBrandVoiceRoute,
  EmbedEmbedBuildRoute: EmbedEmbedBuildRoute,
  EmbedEmbedCampaignBriefRoute: EmbedEmbedCampaignBriefRoute,
  EmbedEmbedCompetitiveAnalyzerRoute: EmbedEmbedCompetitiveAnalyzerRoute,
  EmbedEmbedEvaluateRoute: EmbedEmbedEvaluateRoute,
  EmbedEmbedImageGeneratorRoute: EmbedEmbedImageGeneratorRoute,
  EmbedEmbedPlaygroundRoute: EmbedEmbedPlaygroundRoute,
  EmbedEmbedRegionAdapterRoute: EmbedEmbedRegionAdapterRoute,
  EmbedEmbedRegionalPlaybookRoute: EmbedEmbedRegionalPlaybookRoute,
  EmbedEmbedSubjectOptimizerRoute: EmbedEmbedSubjectOptimizerRoute,
  EmbedEmbedTranslateRoute: EmbedEmbedTranslateRoute,
  EmbedEmbedWebAnalyzerRoute: EmbedEmbedWebAnalyzerRoute,
}

const EmbedRouteWithChildren = EmbedRoute._addFileChildren(EmbedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EmbedRoute: EmbedRouteWithChildren,
  AboutRoute: AboutRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  CopywriterPopoutRoute: CopywriterPopoutRoute,
  EnterpriseRoute: EnterpriseRoute,
  ForAgenciesRoute: ForAgenciesRoute,
  ForEnterpriseRoute: ForEnterpriseRoute,
  HigherEducationMarketingStrategiesRoute:
    HigherEducationMarketingStrategiesRoute,
  LoginRoute: LoginRoute,
  OgPreviewRoute: OgPreviewRoute,
  PrivacyRoute: PrivacyRoute,
  RequestAccessRoute: RequestAccessRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  TryCopywriterRoute: TryCopywriterRoute,
  AgencyRequestAccessRoute: AgencyRequestAccessRoute,
  CompassLockerRoute: CompassLockerRoute,
  CompassSetupRoute: CompassSetupRoute,
  DocsSalesforceCanvasRoute: DocsSalesforceCanvasRoute,
  FeaturesAiCopywriterRoute: FeaturesAiCopywriterRoute,
  FeaturesBrandAuditRoute: FeaturesBrandAuditRoute,
  FeaturesBrandStudioRoute: FeaturesBrandStudioRoute,
  FeaturesContentDnaRoute: FeaturesContentDnaRoute,
  FeaturesEvaluateRoute: FeaturesEvaluateRoute,
  FeaturesImageStudioRoute: FeaturesImageStudioRoute,
  FeaturesJourneyDesignerRoute: FeaturesJourneyDesignerRoute,
  FeaturesLibraryRoute: FeaturesLibraryRoute,
  FeaturesMessageBuilderRoute: FeaturesMessageBuilderRoute,
  FeaturesWebcrawlRoute: FeaturesWebcrawlRoute,
  IntegrationsSalesforceCanvasRoute: IntegrationsSalesforceCanvasRoute,
  CompassIndexRoute: CompassIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  NdaSignSlugRoute: NdaSignSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
