// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.3.0";

// src/lib/mcp/tools/list-profiles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-profiles.ts
var list_profiles_default = defineTool({
  name: "list_profiles",
  title: "List profiles",
  description: "List the organization/institution profiles the signed-in user can access, with their type and status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum profiles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("institutional_profiles").select("id, name, profile_type, parent_profile_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_messages_default = defineTool2({
  name: "list_messages",
  title: "List saved messages",
  description: "List the signed-in user's saved messages, newest first. Optionally filter by profile, channel, or a text search on the title.",
  inputSchema: {
    profile_id: z2.string().uuid().optional().describe("Only messages tied to this profile."),
    channel: z2.string().trim().min(1).optional().describe("Only messages for this channel, e.g. email."),
    search: z2.string().trim().min(1).optional().describe("Case-insensitive title search."),
    limit: z2.number().int().min(1).max(50).default(20).describe("Maximum messages to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ profile_id, channel, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("personal_messages").select("id, title, channel, audience, tone, approved, institutional_profile_id, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (profile_id) query = query.eq("institutional_profile_id", profile_id);
    if (channel) query = query.eq("channel", channel);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-message.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_message_default = defineTool3({
  name: "get_message",
  title: "Get a saved message",
  description: "Fetch the full content and metadata of one saved message by its ID.",
  inputSchema: {
    id: z3.string().uuid().describe("The message ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("personal_messages").select(
      "id, title, content, channel, channels, channel_drafts, audience, cohort, tone, goal, moment, notes, approved, institutional_profile_id, created_at, updated_at"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No message found with that ID." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/create-message.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_message_default = defineTool4({
  name: "create_message",
  title: "Save a message",
  description: "Save a new message for the signed-in user so it appears in their personal library in the app.",
  inputSchema: {
    title: z4.string().trim().min(1).max(200).describe("Short title for the message."),
    content: z4.string().trim().min(1).describe("The message body."),
    channel: z4.string().trim().min(1).optional().describe("Channel, e.g. email, social, letter."),
    audience: z4.string().trim().min(1).optional().describe("Intended audience."),
    tone: z4.string().trim().min(1).optional().describe("Tone of voice."),
    profile_id: z4.string().uuid().optional().describe("Profile this message belongs to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, channel, audience, tone, profile_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error: profileError } = await supabase.from("profiles").select("tenant_id").eq("id", userId).maybeSingle();
    if (profileError) {
      return { content: [{ type: "text", text: profileError.message }], isError: true };
    }
    if (!profile?.tenant_id) {
      return {
        content: [{ type: "text", text: "No workspace found for this account, so the message cannot be saved." }],
        isError: true
      };
    }
    const { data, error } = await supabase.from("personal_messages").insert({
      user_id: userId,
      tenant_id: profile.tenant_id,
      title,
      content,
      channel: channel ?? "email",
      audience: audience ?? null,
      tone: tone ?? null,
      institutional_profile_id: profile_id ?? null,
      source: "mcp"
    }).select("id, title, channel, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${title}" (id ${data?.id}).` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/search-stories.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.3.0";
import { z as z5 } from "npm:zod@^3.25.76";
var search_stories_default = defineTool5({
  name: "search_stories",
  title: "Search story bank",
  description: "Search the story bank the signed-in user can access by title or narrative text, returning matching stories.",
  inputSchema: {
    query: z5.string().trim().min(2).describe("Text to look for in story titles and narratives."),
    profile_id: z5.string().uuid().optional().describe("Only stories tied to this profile."),
    limit: z5.number().int().min(1).max(25).default(10).describe("Maximum stories to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, profile_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const safe = query.replace(/[%,]/g, " ");
    let request = supabase.from("story_bank").select("id, title, story_type, narrative, pull_quote, themes, is_featured, profile_id, created_at").or(`title.ilike.%${safe}%,narrative.ilike.%${safe}%`).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (profile_id) request = request.eq("profile_id", profile_id);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { stories: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yeuwpuzbccqnqdlnjhfm";
var mcp_default = defineMcp({
  name: "campusvoice-ai",
  title: "CampusVoice.ai",
  version: "0.1.0",
  instructions: "Tools for CampusVoice.ai. Use `list_profiles` to find the user's profiles, `list_messages` and `get_message` to read their saved messages, `create_message` to save new copy into their library, and `search_stories` to pull supporting stories from the story bank. All calls act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_profiles_default, list_messages_default, get_message_default, create_message_default, search_stories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.3.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
